-- =====================================================================
-- VERIFICACIÓN DE CAJONES (2026-10-06) — pedido de Elías Irace para Alan Gonzalez (Logística)
-- =====================================================================
-- "A las 3 de la tarde le tiene que aparecer: buscá y revisá los siguientes cajones, con quién lo
-- hizo, a qué hora, cuántas unidades, en qué sector se pudo haber guardado, el peso que tendría que
-- tener y el peso por unidad (todo en KG)". "Solo van a ser 2 cajones por día", "solo Cervantes",
-- "el envasado no tiene peso", y el que verifica no sabe en qué cajón físico se guardó: lo elige
-- (la tara sale de GP2.cajon). Y "se va a registrar cuando empezó y cuando terminó" — no quién.
--
-- REGLA 0: el cajón es una fila de public.db_n8n_espejo (el registro de producción de Cervantes;
-- GP2.produccion casi no se usa: 3 filas en 8 días). Igual que el contador de Unidades sin
-- accidente (public.gp2_matriz_racha_sync -> GP2.matriz_racha), el que lee public es UNA función
-- que vive en public y COPIA lo necesario a una tabla GP2. Las RPC de pantalla leen sólo GP2.
--
-- De dónde sale cada dato (medido el 06/10/2026):
--   * Se descartan: lo que no es producción (LT, MOV, PB, AL: Uni 0), lo borrado (Eliminar = 'S'),
--     los "[CONT]" (cajón que viene del día anterior: mezcla dos días) y el ENVASADO
--     (public."Matrices"."Tipo_Matriz" = 'E', 96 matrices).
--   * PESO POR UNIDAD: GP2.matriz.n_matriz -> ruta_paso.comp_salida_id -> componente.kg_x_uni.
--     Sólo 15 de las 38 matrices usadas en 14 días lo tienen (49% de los cajones): el sorteo
--     elige PRIMERO entre los que tienen peso y completa con los que no.
--     Una matriz puede sacar más de una pieza (la 12: 0,0355 / 0,0388 / 0,0396 kg): se guarda el
--     rango y el peso esperado es "entre X y Y". La 501 (piedra) se carga en KG
--     (GP2.matriz.carga_en = 'kg'): su peso esperado son las unidades cargadas.
--   * SECTOR donde puede estar = el sector de esa pieza (componente.sector_id).
--   * Entre los que tienen peso, de operarios DISTINTOS: el 05/10, 9 de los 11 cajones con peso
--     eran de la misma persona y la misma matriz.
--
-- Todo queda COPIADO al sortear: si después cambia GP2 o el registro de producción, lo verificado
-- sigue diciendo lo que decía ese día.
--
-- ↩ Revertir:
--   select cron.unschedule('gp2-verif-cajones-15h');
--   drop function public.gp2_verif_cajones_sortear(date), public._gp2_verif_candidatos(date);
--   drop function "GP2".verif_cajones_bundle(date), "GP2".verif_cajones_empezar(date),
--     "GP2".verif_cajon_cargar(bigint, integer, numeric, boolean, text);
--   drop table "GP2".verif_cajon; drop table "GP2".verif_cajon_dia;

-- ── El día: cuándo se sortearon, cuándo empezó la verificación y cuándo terminó.
create table if not exists "GP2".verif_cajon_dia (
  fecha        date        primary key,
  sorteado_en  timestamptz not null default now(),
  empezado_en  timestamptz,
  terminado_en timestamptz,
  constraint verif_cajon_dia_orden_ck check (terminado_en is null or (empezado_en is not null and terminado_en >= empezado_en))
);
comment on table "GP2".verif_cajon_dia is 'Verificación de cajones: un día. empezado_en lo marca el botón Empezar; terminado_en se sella solo al resolver el último cajón del día (no se pisa si después se corrige un peso).';

-- ── Los cajones sorteados (2 por día), con todo lo que se mostró y lo que dio la balanza.
create table if not exists "GP2".verif_cajon (
  id              bigint generated by default as identity primary key,
  fecha           date        not null references "GP2".verif_cajon_dia(fecha),
  espejo_id       bigint      not null,
  legajo          text,
  operario        text,
  matriz          text,
  nombre_matriz   text,
  uni             numeric     not null,
  carga_en        text,
  hora_inicio     time,
  hora_fin        time,
  piezas          jsonb       not null default '[]'::jsonb,
  kg_x_uni_min    numeric,
  kg_x_uni_max    numeric,
  kg_esperado_min numeric,
  kg_esperado_max numeric,
  sectores        text,
  resultado       text,
  cajon_numero    integer,
  tara_kg         numeric,
  peso_bruto_kg   numeric,
  peso_neto_kg    numeric,
  cargado_en      timestamptz,
  nota            text,
  constraint verif_cajon_fecha_espejo_key unique (fecha, espejo_id),
  constraint verif_cajon_resultado_ck check (resultado is null or resultado in ('pesado', 'no_encontrado')),
  constraint verif_cajon_pesado_ck check (resultado is distinct from 'pesado'
    or (cajon_numero is not null and peso_bruto_kg is not null and peso_neto_kg is not null)),
  constraint verif_cajon_no_encontrado_ck check (resultado is distinct from 'no_encontrado'
    or nullif(btrim(coalesce(nota, '')), '') is not null)
);
comment on table "GP2".verif_cajon is 'Verificación de cajones: copia del registro de producción (public.db_n8n_espejo.id = espejo_id) al sortearlo, más el peso de la balanza. La llena public.gp2_verif_cajones_sortear (cron 15:00).';
comment on column "GP2".verif_cajon.carga_en is 'GP2.matriz.carga_en: unidades | golpes | kg. Con kg, el peso esperado es uni.';
comment on column "GP2".verif_cajon.piezas is '[{codigo, descripcion, kg_x_uni, sector}] de las piezas que saca la matriz según GP2.';
comment on column "GP2".verif_cajon.resultado is 'pesado | no_encontrado (con nota obligatoria). null = falta.';

alter table "GP2".verif_cajon_dia enable row level security;
alter table "GP2".verif_cajon     enable row level security;
revoke all on "GP2".verif_cajon_dia from anon, authenticated;
revoke all on "GP2".verif_cajon     from anon, authenticated;

-- ── Los candidatos de un día: cajones de Cervantes con unidades, sin envasado, sin [CONT], que no
--    estén ya sorteados. Con las piezas que saca la matriz según GP2 (peso por unidad y sector).
create or replace function public._gp2_verif_candidatos(p_fecha date)
returns table (id bigint, legajo text, operario text, matriz text, nombre_matriz text, uni numeric,
               carga_en text, hora_inicio time, hora_fin time, piezas jsonb,
               kmin numeric, kmax numeric, sectores text)
language sql stable security definer
set search_path = public
as $$
  select t.id, t.legajo, t.operario, t.matriz, t.nombre_matriz, t.uni, t.carga_en, t.hora_inicio, t.hora_fin, t.piezas,
         (select min((j->>'kg_x_uni')::numeric) from jsonb_array_elements(t.piezas) j where (j->>'kg_x_uni')::numeric > 0),
         (select max((j->>'kg_x_uni')::numeric) from jsonb_array_elements(t.piezas) j where (j->>'kg_x_uni')::numeric > 0),
         (select string_agg(distinct j->>'sector', ' / ') from jsonb_array_elements(t.piezas) j where j->>'sector' is not null)
    from (
      select e.id, e."Legajo" as legajo, e."Nombre_Empleado" as operario, e."Matriz" as matriz,
             e."Nombre_Matriz" as nombre_matriz, e."Uni"::numeric as uni,
             (select gm.carga_en from "GP2".matriz gm where gm.n_matriz = e."Matriz" limit 1) as carga_en,
             e."Hora_Inicio" as hora_inicio, e."Hora_Fin" as hora_fin,
             (select coalesce(jsonb_agg(distinct jsonb_build_object(
                       'codigo', c.codigo, 'descripcion', c.descripcion, 'kg_x_uni', c.kg_x_uni, 'sector', s.nombre)),
                     '[]'::jsonb)
                from "GP2".matriz gm
                join "GP2".ruta_paso rp on rp.matriz_id = gm.id
                join "GP2".componente c on c.id = rp.comp_salida_id
                left join "GP2".sector s on s.id = c.sector_id
               where gm.n_matriz = e."Matriz") as piezas
        from public.db_n8n_espejo e
       where (e."Fecha" at time zone 'America/Argentina/Buenos_Aires')::date = p_fecha
         and coalesce(e."Eliminar", '') <> 'S'
         and coalesce(e."Uni", 0) >= 1
         and coalesce(e."Matriz", '') <> ''
         and coalesce(e."Nombre_Matriz", '') not like '[CONT]%'
         and not exists (select 1 from public."Matrices" pm
                          where pm."N_Matriz" = e."Matriz" and pm."Tipo_Matriz" = 'E')      -- envasado
         and coalesce(e."Nombre_Matriz", '') !~* '^(re)?env'
         and not exists (select 1 from "GP2".verif_cajon v where v.fecha = p_fecha and v.espejo_id = e.id)
    ) t;
$$;
revoke all on function public._gp2_verif_candidatos(date) from public, anon, authenticated;

-- ── El sorteo. Vive en public porque LEE public (el espejo y el maestro de matrices); escribe GP2.
--    Idempotente: si ese día ya tiene 2, no hace nada. Sin producción elegible, no crea el día.
create or replace function public.gp2_verif_cajones_sortear(p_fecha date default null)
returns integer
language plpgsql security definer
set search_path = public
as $$
declare
  v_fecha date := coalesce(p_fecha, (now() at time zone 'America/Argentina/Buenos_Aires')::date);
  v_faltan integer;
  v_n integer := 0;
begin
  perform pg_advisory_xact_lock(hashtextextended('gp2_verif_cajones:' || v_fecha::text, 0));
  v_faltan := 2 - (select count(*) from "GP2".verif_cajon v where v.fecha = v_fecha);
  if v_faltan <= 0 then return 0; end if;
  if not exists (select 1 from public._gp2_verif_candidatos(v_fecha)) then return 0; end if;

  insert into "GP2".verif_cajon_dia (fecha) values (v_fecha) on conflict (fecha) do nothing;

  -- Primero los que tienen peso (o se cargan en kg); entre ésos, de operarios DISTINTOS.
  insert into "GP2".verif_cajon (fecha, espejo_id, legajo, operario, matriz, nombre_matriz, uni, carga_en,
                                 hora_inicio, hora_fin, piezas, kg_x_uni_min, kg_x_uni_max,
                                 kg_esperado_min, kg_esperado_max, sectores)
  select v_fecha, x.id, x.legajo, x.operario, x.matriz, x.nombre_matriz, x.uni, x.carga_en,
         x.hora_inicio, x.hora_fin, x.piezas, x.kmin, x.kmax,
         case when x.carga_en = 'kg' then x.uni else round(x.kmin * x.uni, 3) end,
         case when x.carga_en = 'kg' then x.uni else round(x.kmax * x.uni, 3) end,
         x.sectores
    from public._gp2_verif_candidatos(v_fecha) x
   order by (x.kmin is not null or x.carga_en = 'kg') desc,
            (x.legajo in (select v.legajo from "GP2".verif_cajon v where v.fecha = v_fecha)) asc,
            row_number() over (partition by x.legajo, (x.kmin is not null or x.carga_en = 'kg') order by random()) asc,
            random()
   limit v_faltan;
  get diagnostics v_n = row_count;
  return v_n;
end;
$$;
comment on function public.gp2_verif_cajones_sortear(date) is 'Verificación de cajones (GP2): sortea 2 cajones de Cervantes del día (sin envasado ni [CONT]) y los copia a GP2.verif_cajon. Vive en public porque lee public.db_n8n_espejo (mismo patrón que gp2_matriz_racha_sync). Cron gp2-verif-cajones-15h.';
revoke all on function public.gp2_verif_cajones_sortear(date) from public, anon, authenticated;

-- ── Lo que dibuja la pantalla (y el cartel de las 15:00): un día, las taras y los últimos días.
create or replace function "GP2".verif_cajones_bundle(p_fecha date default null)
returns jsonb
language plpgsql stable security definer
set search_path = "GP2"
as $$
declare
  v_hoy   date := (now() at time zone 'America/Argentina/Buenos_Aires')::date;
  v_fecha date := coalesce(p_fecha, (now() at time zone 'America/Argentina/Buenos_Aires')::date);
begin
  return jsonb_build_object(
    'fecha',   v_fecha,
    'hoy',     v_hoy,
    'dia',     (select to_jsonb(d) from "GP2".verif_cajon_dia d where d.fecha = v_fecha),
    'cajones', coalesce((select jsonb_agg(to_jsonb(v) order by v.id) from "GP2".verif_cajon v where v.fecha = v_fecha), '[]'::jsonb),
    'taras',   coalesce((select jsonb_agg(jsonb_build_object('numero', c.numero, 'tara_kg', c.tara_kg, 'descripcion', c.descripcion)
                                          order by c.numero) from "GP2".cajon c), '[]'::jsonb),
    'dias',    coalesce((select jsonb_agg(x order by x.fecha desc) from (
                  select d.fecha, d.sorteado_en, d.empezado_en, d.terminado_en,
                         (select count(*) from "GP2".verif_cajon v where v.fecha = d.fecha) as cajones,
                         (select count(*) from "GP2".verif_cajon v where v.fecha = d.fecha and v.resultado is not null) as resueltos
                    from "GP2".verif_cajon_dia d order by d.fecha desc limit 20) x), '[]'::jsonb));
end;
$$;

-- ── ▶ Empezar: sella la hora en que empezó la verificación del día (la primera vez; después no la pisa).
create or replace function "GP2".verif_cajones_empezar(p_fecha date)
returns jsonb
language plpgsql security definer
set search_path = "GP2"
as $$
begin
  update "GP2".verif_cajon_dia d set empezado_en = coalesce(d.empezado_en, now()) where d.fecha = p_fecha;
  if not found then
    raise exception 'No hay cajones sorteados para el %', to_char(p_fecha, 'DD/MM/YYYY') using errcode = 'P0002';
  end if;
  return "GP2".verif_cajones_bundle(p_fecha);
end;
$$;

-- ── Cargar un cajón: el peso que marcó la balanza y en qué cajón físico (la tara), o "no lo encontré"
--    con una nota. Se puede corregir (queda lo último). Al resolver el último del día se sella el fin.
create or replace function "GP2".verif_cajon_cargar(p_id bigint, p_cajon integer default null, p_bruto_kg numeric default null,
                                                    p_no_encontrado boolean default false, p_nota text default null)
returns jsonb
language plpgsql security definer
set search_path = "GP2"
as $$
declare
  v_fecha date;
  v_empezo timestamptz;
  v_tara numeric;
  v_nota text := nullif(btrim(coalesce(p_nota, '')), '');
begin
  select v.fecha, d.empezado_en into v_fecha, v_empezo
    from "GP2".verif_cajon v join "GP2".verif_cajon_dia d on d.fecha = v.fecha
   where v.id = p_id;
  if not found then raise exception 'No encontré ese cajón' using errcode = 'P0002'; end if;
  if v_empezo is null then
    raise exception 'Primero apretá ▶ Empezar: así queda registrada la hora en que empezó la verificación' using errcode = '22023';
  end if;

  if coalesce(p_no_encontrado, false) then
    if v_nota is null then
      raise exception 'Si no encontraste el cajón, escribí qué pasó (dónde lo buscaste)' using errcode = '22023';
    end if;
    update "GP2".verif_cajon v
       set resultado = 'no_encontrado', cajon_numero = null, tara_kg = null, peso_bruto_kg = null, peso_neto_kg = null,
           nota = v_nota, cargado_en = now()
     where v.id = p_id;
  else
    select c.tara_kg into v_tara from "GP2".cajon c where c.numero = p_cajon;
    if not found then raise exception 'Elegí en qué cajón lo pesaste (N° 1 a 10)' using errcode = '22023'; end if;
    if p_bruto_kg is null or p_bruto_kg <= v_tara then
      raise exception 'El peso de la balanza tiene que ser mayor que la tara del cajón N° % (% kg)',
        p_cajon, replace(v_tara::text, '.', ',') using errcode = '22023';
    end if;
    if p_bruto_kg > 300 then
      raise exception 'Más de 300 kg no puede ser un cajón: revisá el número' using errcode = '22023';
    end if;
    update "GP2".verif_cajon v
       set resultado = 'pesado', cajon_numero = p_cajon, tara_kg = v_tara, peso_bruto_kg = round(p_bruto_kg, 3),
           peso_neto_kg = round(p_bruto_kg - v_tara, 3), nota = v_nota, cargado_en = now()
     where v.id = p_id;
  end if;

  update "GP2".verif_cajon_dia d set terminado_en = now()
   where d.fecha = v_fecha and d.terminado_en is null
     and not exists (select 1 from "GP2".verif_cajon v where v.fecha = v_fecha and v.resultado is null);

  return "GP2".verif_cajones_bundle(v_fecha);
end;
$$;

revoke all on function "GP2".verif_cajones_bundle(date) from public;
revoke all on function "GP2".verif_cajones_empezar(date) from public;
revoke all on function "GP2".verif_cajon_cargar(bigint, integer, numeric, boolean, text) from public;
grant execute on function "GP2".verif_cajones_bundle(date) to anon, authenticated;
grant execute on function "GP2".verif_cajones_empezar(date) to anon, authenticated;
grant execute on function "GP2".verif_cajon_cargar(bigint, integer, numeric, boolean, text) to anon, authenticated;

-- ── El reloj: 15:00 de Argentina = 18:00 UTC, todos los días (sin producción, no sortea nada).
select cron.schedule('gp2-verif-cajones-15h', '0 18 * * *', 'select public.gp2_verif_cajones_sortear()');
