-- =====================================================================
-- 2026-09-30 — D4: LO QUE CERVANTES MANDA A VIRGILIO LE LLEGA COMO AVISO SÍ / NO (GP2 v1.220.0)
--
-- [Thomas 30/09, "D4 si"] Regla general Cervantes <-> Virgilio (CLAUDE.md): el que RECIBE dice Sí / No
-- donde trabaja; el Sí va por el MISMO camino que la carga manual; cada lado toca SÓLO su fila y la
-- reacción del otro lado la hace un trigger de ESE lado, que se ve donde se cargó.
--
--   · GP2.envio_virgilio: la frontera GP2 -> Virgilio. Una fila por pieza que la tablet manda
--     (Enviar -> Virgilio). La escribe enviar_a_virgilio; el estado lo cambian las funciones
--     public.gv_envio_cervantes_* de Gestión Virgilio (sql/gv_envio_cervantes_v2540.sql de ese repo).
--   · fn_envio_virgilio_denegado (trigger de GP2): cuando Virgilio dice No, devuelve el stock acá —
--     el terminado vuelve a "Art. Terminado (Fábrica)" (ajuste), el insumo / SC / SP vuelve del
--     depósito de Virgilio a su sector (traslado). Si falla, queda en revertido_error y en la vista
--     v_envio_virgilio_sin_revertir.
--   · tablet_bundle: cada pieza de Enviar -> Virgilio dice lo que espera el Sí y lo que Virgilio denegó
--     en los últimos 15 días («⛔ Denegado por Virgilio»).
--   · fn_entregas_virgilio_espejo: el origen interno (Fábrica) ya no descuenta el despiece (lo hace
--     fabrica_producir); el trigger está apagado, esto es para que no cuente doble si se prende.
-- =====================================================================

-- ---------- 1) la frontera ----------
create table if not exists "GP2".envio_virgilio (
  id bigint generated by default as identity primary key,
  creado_en timestamptz not null default now(),
  creado_por text,
  componente_id bigint not null references "GP2".componente(id),
  codigo text not null,
  descripcion text,
  grupo text not null,
  cantidad numeric not null,
  unidad text not null,
  cajas numeric,
  articulos_por_caja numeric,
  movimiento_id bigint references "GP2".movimiento(id) on delete set null,
  estado text not null default 'pendiente',
  confirmado_en timestamptz, confirmado_por text, gv_ref text,
  denegado_en timestamptz, denegado_por text, denegado_motivo text,
  revertido_en timestamptz, revertido_movimiento_id bigint, revertido_error text,
  constraint envio_virgilio_grupo_chk check (grupo in ('terminado','insumo','sc','sp')),
  constraint envio_virgilio_unidad_chk check (unidad in ('uni','kg')),
  constraint envio_virgilio_cantidad_chk check (cantidad > 0),
  constraint envio_virgilio_estado_chk check (estado in ('pendiente','confirmado','denegado'))
);
create index if not exists envio_virgilio_pend_idx on "GP2".envio_virgilio (estado, componente_id);
comment on table "GP2".envio_virgilio is
  '2026-09-30 (D4): lo que Cervantes le manda a Virgilio desde la tablet (Enviar -> Virgilio), una fila por pieza. '
  'La escribe enviar_a_virgilio. Virgilio dice Sí / No donde recibe (public.gv_envio_cervantes_confirmar / _denegar); '
  'el No lo devuelve acá el trigger fn_envio_virgilio_denegado. cantidad en la unidad canónica (uni o kg).';
alter table "GP2".envio_virgilio enable row level security;
drop policy if exists p_gp2_select on "GP2".envio_virgilio;
create policy p_gp2_select on "GP2".envio_virgilio for select to anon, authenticated using (true);
revoke all on "GP2".envio_virgilio from anon, authenticated;
grant select on "GP2".envio_virgilio to anon, authenticated;

-- ---------- 2) el No de Virgilio devuelve el stock acá ----------
create or replace function "GP2".fn_envio_virgilio_denegado()
 returns trigger language plpgsql security definer set search_path to 'GP2'
as $function$
declare v_sec bigint; v_o bigint; v_d bigint; v_mov bigint;
begin
  if not (old.estado = 'pendiente' and new.estado = 'denegado') then return new; end if;
  begin
    if new.grupo = 'terminado' then
      v_d := ubic_de('art_terminado', 3);
      insert into movimiento(fecha, tipo_mov, comp_id, ubic_origen_id, ubic_destino_id, cantidad,
                             unidad_origen, unidad_destino, nota)
      values (now(), 'ajuste', new.componente_id, null, v_d, new.cantidad, 'uni', 'uni',
              'Denegado por Virgilio (envío #' || new.id || ')')
      returning id into v_mov;
    else
      select sector_id into v_sec from componente where id = new.componente_id;
      v_o := ubic_de('virgilio_sector', v_sec);
      v_d := ubic_de('sector', v_sec);
      if v_o is null or v_d is null then raise exception 'falta la ubicacion del sector % o su deposito en Virgilio', v_sec; end if;
      insert into movimiento(fecha, tipo_mov, comp_id, ubic_origen_id, ubic_destino_id, cantidad,
                             unidad_origen, unidad_destino, nota)
      values (now(), 'traslado', new.componente_id, v_o, v_d, new.cantidad, new.unidad, new.unidad,
              'Denegado por Virgilio (envío #' || new.id || ')')
      returning id into v_mov;
    end if;
    new.revertido_en := now();
    new.revertido_movimiento_id := v_mov;
    new.revertido_error := null;
  exception when others then
    -- el No de Virgilio NO se frena: queda anotado y a la vista (v_envio_virgilio_sin_revertir)
    new.revertido_error := sqlerrm;
  end;
  return new;
end $function$;
revoke execute on function "GP2".fn_envio_virgilio_denegado() from public, anon, authenticated;
drop trigger if exists trg_envio_virgilio_denegado on "GP2".envio_virgilio;
create trigger trg_envio_virgilio_denegado before update of estado on "GP2".envio_virgilio
  for each row execute function "GP2".fn_envio_virgilio_denegado();

create or replace view "GP2".v_envio_virgilio_sin_revertir with (security_invoker = true) as
  select id, creado_en, codigo, descripcion, cantidad, unidad, denegado_en, denegado_por, denegado_motivo, revertido_error
    from "GP2".envio_virgilio
   where estado = 'denegado' and revertido_en is null;
comment on view "GP2".v_envio_virgilio_sin_revertir is
  'D4: envíos que Virgilio denegó y GP2 no pudo devolver al stock (revertido_error dice por qué). Vacía = todo bien.';
grant select on "GP2".v_envio_virgilio_sin_revertir to anon, authenticated;

-- ---------- 3) enviar_a_virgilio escribe la frontera ----------
CREATE OR REPLACE FUNCTION "GP2".enviar_a_virgilio(p_comp_id bigint, p_cantidad numeric, p_unidad text DEFAULT NULL::text, p_fecha timestamp with time zone DEFAULT now(), p_nota text DEFAULT NULL::text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'GP2'
AS $function$
declare v_sec bigint; v_um text; v_cod text; v_u text; v_o bigint; v_d bigint; v_mov bigint;
        v_f timestamptz := coalesce(p_fecha, now()); v_desc text; v_env bigint;
        -- quien lo manda (el mail de la sesion de la tablet), para el aviso que ve Virgilio
        v_por text := coalesce(nullif(lower(nullif(current_setting('request.jwt.claims', true), '')::jsonb->>'email'), ''), current_user);
begin
  perform "GP2"._exigir_autorizado();
  if p_cantidad is null or p_cantidad <= 0 then raise exception 'La cantidad debe ser mayor a 0'; end if;
  select sector_id, unidad_medida, codigo, descripcion into v_sec, v_um, v_cod, v_desc from componente where id = p_comp_id;
  if v_sec is null then raise exception 'El componente % no existe', p_comp_id; end if;
  v_u := case when lower(coalesce(p_unidad, v_um, 'uni')) = 'kg' then 'kg' else 'uni' end;
  if v_sec = 12 then
    -- ART. TERMINADO de Fábrica: sale de "Art. Terminado (Fábrica)" y ahí termina el proceso
    if not exists (select 1 from articulo a join ruta r on r.articulo_id = a.id
                     join ruta_paso rp on rp.ruta_id = r.id and rp.tallerista_id = 3
                    where upper(a.codigo) = upper(v_cod)) then
      raise exception 'El artículo % no lo arma Fábrica: no sale de acá.', v_cod;
    end if;
    v_o := ubic_de('art_terminado', 3);
    insert into movimiento(fecha, tipo_mov, comp_id, ubic_origen_id, ubic_destino_id, cantidad,
                           unidad_origen, unidad_destino, nota)
    values (v_f, 'recepcion_virgilio', p_comp_id, v_o, null, p_cantidad, 'uni', 'uni',
            coalesce(p_nota, 'Enviado a Virgilio (tablet)'))
    returning id into v_mov;
    -- AVISO A VIRGILIO (D4, 2026-09-30): queda en la frontera hasta que Virgilio diga Si / No
    -- donde recibe. Si dice No, el trigger fn_envio_virgilio_denegado lo devuelve aca.
    insert into envio_virgilio(creado_por, componente_id, codigo, descripcion, grupo, cantidad, unidad,
                               cajas, articulos_por_caja, movimiento_id)
    select v_por, p_comp_id, v_cod, coalesce(a.descripcion, v_desc), 'terminado', p_cantidad, 'uni',
           case when a.articulos_por_caja > 0 then round(p_cantidad / a.articulos_por_caja, 4) end,
           a.articulos_por_caja, v_mov
      from (select 1) x left join articulo a on upper(a.codigo) = upper(v_cod)
     limit 1
    returning id into v_env;
    return jsonb_build_object('ok', true, 'movimiento_id', v_mov, 'destino', 'virgilio', 'envio_id', v_env,
      'stock_art_terminado', (select cantidad from inventario where componente_id = p_comp_id and ubicacion_id = v_o));
  end if;
  if v_sec not in (1, 2, 5, 6, 11) then
    raise exception '% : del sector % no se manda a Virgilio desde la tablet (solo SC, SP, fleje, plástico y caja).', v_cod, v_sec;
  end if;
  v_o := ubic_de('sector', v_sec);
  v_d := ubic_de('virgilio_sector', v_sec);
  if v_o is null or v_d is null then raise exception '% : falta la ubicación del sector o su depósito en Virgilio.', v_cod; end if;
  insert into movimiento(fecha, tipo_mov, comp_id, ubic_origen_id, ubic_destino_id, cantidad,
                         unidad_origen, unidad_destino, nota)
  values (v_f, 'traslado', p_comp_id, v_o, v_d, p_cantidad, v_u, v_u, coalesce(p_nota, 'Enviado a Virgilio (tablet)'))
  returning id into v_mov;
  insert into envio_virgilio(creado_por, componente_id, codigo, descripcion, grupo, cantidad, unidad, movimiento_id)
  values (v_por, p_comp_id, v_cod, v_desc, case v_sec when 1 then 'sc' when 2 then 'sp' else 'insumo' end,
          p_cantidad, v_u, v_mov)
  returning id into v_env;
  return jsonb_build_object('ok', true, 'movimiento_id', v_mov, 'destino', 'virgilio_sector', 'envio_id', v_env,
    'stock_cervantes', (select cantidad from inventario where componente_id = p_comp_id and ubicacion_id = v_o),
    'stock_virgilio',  (select cantidad from inventario where componente_id = p_comp_id and ubicacion_id = v_d));
end $function$
;

-- ---------- 4) tablet_bundle: lo que espera el Sí y lo denegado ----------
CREATE OR REPLACE FUNCTION "GP2".tablet_bundle()
 RETURNS jsonb
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'GP2'
AS $function$
with
-- FABRICA (tallerista 3, 2026-09-30): lo que arma Fabrica. A Fabrica no se le mandan partes: se le
-- MANDA A PRODUCIR el articulo en cajas (Enviar -> Talleristas -> Fabrica), que descuenta el despiece
-- y suma el terminado en la ubicacion "Art. Terminado (Fabrica)"; desde ahi se manda a Virgilio
-- (Enviar -> Virgilio). [usuario 2026-09-30]
fab as materialized (
  select distinct a.id art_id, a.codigo, a.articulos_por_caja uxc, c.id comp_id
    from articulo a
    join ruta r on r.articulo_id = a.id
    join ruta_paso rp on rp.ruta_id = r.id and rp.tallerista_id = 3
    join componente c on upper(c.codigo) = upper(a.codigo) and c.sector_id = 12
   where not a.discontinuado and not coalesce(c.discontinuado, false)
),
-- FASONERO (proveedor_servicio.pedido_por_oc, hoy Maspoli): lo que falta entregar de su O.C.
-- ENVIADA, sumado por (proveedor, pieza que se le manda). Es el techo de lo que hay que mandarle:
-- si nos debe 10 mangos, hay que tener 10 virolas en su poder [usuario 2026-09-18]. Mismo criterio
-- que el inyector (rep_iny): el borrador es un pedido que todavia no salio y no dispara envio.
oc_ps as (
  select p.proveedor_id, p.comp_entrada_id as comp_id, sum(coalesce(x.pend,0)) as pend
    from (select distinct rp.proveedor_id, rp.comp_entrada_id, rp.comp_salida_id
            from ruta_paso rp
            join proveedor_servicio ps on ps.id = rp.proveedor_id and ps.pedido_por_oc
           where rp.tipo_paso = 'proveedor_servicio' and rp.comp_entrada_id is not null) p
    left join lateral (
       select sum(oi.cantidad - coalesce(oi.recibido,0)) as pend
         from orden_compra_item oi join orden_compra o on o.id = oi.oc_id
        where oi.componente_id = p.comp_salida_id and o.estado = 'enviada'
          and oi.cantidad > coalesce(oi.recibido,0)
    ) x on true
   group by p.proveedor_id, p.comp_entrada_id
),
env as (
  select v.tipo, v.ref_id::text as ref, v.comp_id
    from v_contraparte_parte v
   where v.lado = 'entrada'
     and ( (v.tipo = 'tallerista'
            and exists (select 1 from tallerista t where t.id = v.ref_id and t.activo and t.id <> 3))
        or (v.tipo = 'proveedor_servicio'
            -- los PS hibridos (Charcas/Eclipse) NO se envian desde la tablet: la entrega de su
            -- materia prima se registra solo en el modulo Casos especiales [usuario 2026-09-17].
            -- el FASONERO aparece SIEMPRE, igual que el inyector: sin O.C. su sugerido es 0 y sube
            -- cuando la orden sale [usuario 2026-09-18: "los inyectores por mas que no este
            -- cargada la orden de compra aparecen igual con cero sugerido, tendria que aparecer
            -- Maspoli con cero sugerido y cuando sale la orden de compra ahi sube el sugerido de
            -- entrega de virolas"]. El techo lo pone oc_ps en la CTE rep, que sin O.C. da 0.
            and exists (select 1 from proveedor_servicio ps where ps.id = v.ref_id and not ps.hibrido)) )
  union all
  select 'proveedor_at', apa.proveedor_at_id::text, ac.componente_id
    from articulo_prov_at apa
    join articulo a on a.codigo = apa.cod_art and not a.discontinuado
    join articulo_componente ac on ac.articulo_id = a.id
    join componente c on c.id = ac.componente_id
   where coalesce(apa.activo,true)
     and c.sector_id in (10,11) and not coalesce(c.discontinuado,false)
  union all
  select 'inyector', c.proveedor, c.material_id
    from componente c
   where c.material_id is not null and c.estado_compra is null and c.proveedor is not null
     and exists (select 1 from proveedor_insumo pi where pi.nombre = c.proveedor)
   group by c.proveedor, c.material_id
  union all
  -- FABRICA: sus articulos terminados (se cargan en cajas)
  select 'tallerista', '3', f.comp_id from fab f
  union all
  -- VIRGILIO (2026-09-30): art. terminados de Fabrica + insumos (plastico, fleje, caja) + SC y SP.
  -- Los importados no: esos los TRAE Virgilio (Recibir -> Virgilio).
  select 'virgilio', 'virgilio', f.comp_id from fab f
  union all
  select 'virgilio', 'virgilio', c.id
    from componente c
   where c.sector_id in (1, 2, 5, 6, 11) and not coalesce(c.discontinuado, false)
     and coalesce(c.estado_compra, '') <> 'importado'
),
-- rep (Enviar a PS / tallerista): el Maximo y el Sugerido salen del CONSUMO DE LA PIEZA QUE SE
-- ENVIA (la entrada), no de la salida. [usuario 2026-09-17: "sale del consumo de estadistica
-- madre x max de meses por ubicacion"]. Antes se calculaba sobre la SALIDA (inventario.maximo de
-- la pieza procesada/armada): las salidas de tallerista son nodos "X Terminado" del sector 12 que
-- no tienen demanda ni maximo cargado, asi que el 90% de las filas salia en 0 (Martin 6 de 94).
-- Ahora maximo = consumo(entrada) x meses_stock de la ubicacion del sector de la entrada:
--   · tallerista -> v_consumo_tallerista (la demanda YA repartida entre los que hacen el paso,
--     via v_reparto_efectivo; asi no se le pide un mes entero a cada uno de dos que arman lo mismo),
--   · PS         -> v_consumo_componente (demanda total de la pieza),
--   · PROV AT    -> v_consumo_prov_at (la demanda del articulo repartida entre los prov AT que lo
--     entregan y los talleristas que lo arman; sin reparto dictado, partes iguales) [usuario
--     2026-09-23: "el inventario maximo de los prov de art terminado tiene que ser al igual que
--     los talleristas de un mes de consumo... si hay mas de uno dividir segun la proporcion"],
--   · fleje (sector 5, en kg) -> v_consumo_fleje_kg (kg/mes) para cualquiera de los dos tipos.
-- Sugerido = maximo − lo que el tercero ya tiene (inventario en su ubicacion). meses_stock cae a 1
-- si la ubicacion no lo tiene (mismo default que OC). OJO, la ubicacion de la que salen los MESES
-- no es la misma para todos: el tallerista y el P.S. la toman del SECTOR de la pieza (como estaba),
-- y el prov AT de SU PROPIA ubicacion, que es donde vive el "un mes" que pidio el usuario. El consumo ya viene en la unidad de la
-- entrada (kg para fleje, uni para el resto), asi que no hay factor de conversion.
-- CONSUMOS, UNA sola vez (2026-09-22): antes se consultaban las tres vistas de consumo fila por
-- fila dentro de rep (una subconsulta correlacionada por cada pieza x destino), y cada vista es
-- un agregado de 30-40 ms. Materializadas aca se calculan una vez y rep las cruza por join:
-- tablet_bundle bajo de ~700 ms a ~200 ms con el mismo resultado.
cons_fk   as materialized (select componente_id, consumo_kg_mes from v_consumo_fleje_kg),
cons_tall as materialized (select tallerista_id, componente_id, uni_mes from v_consumo_tallerista),
cons_comp as materialized (select componente_id, consumo_uni_mes from v_consumo_componente),
cons_pat  as materialized (select proveedor_at_id, componente_id, uni_mes from v_consumo_prov_at),
rep as (
  select e.tipo, e.ref, e.comp_id,
         round(t.techo) as maximo_dest,
         null::numeric as stock_dest,   -- el front muestra saldo_dest como "Stock", no este
         greatest(0, round(
            t.techo
            - coalesce((select i.cantidad from inventario i
                         where i.componente_id = e.comp_id
                           and i.ubicacion_id = ubic_de(e.tipo, e.ref::bigint) limit 1),0)
         , 2)) as sugerido
    from (select distinct tipo, ref, comp_id from env
           where tipo in ('proveedor_servicio','tallerista','proveedor_at')
             -- Fabrica no tiene sugerido: se le manda a producir lo que se decida (2026-09-30)
             and not (tipo = 'tallerista' and ref = '3')) e
    join componente ent on ent.id = e.comp_id
    left join cons_fk   fk on fk.componente_id = e.comp_id
    left join cons_tall ct on ct.componente_id = e.comp_id and e.tipo = 'tallerista'
                          and ct.tallerista_id = e.ref::bigint
    left join cons_pat cpa on cpa.componente_id = e.comp_id and e.tipo = 'proveedor_at'
                          and cpa.proveedor_at_id = e.ref::bigint
    left join cons_comp vc on vc.componente_id = e.comp_id
    cross join lateral (
       select
         coalesce((select u.meses_stock from ubicacion u
                    where u.id = case when e.tipo = 'proveedor_at'
                                        then ubic_de('proveedor_at', e.ref::bigint)
                                      -- el tallerista se surte de UN mes (regla del usuario 2026-09-23:
                                      -- "los talleristas de un mes de consumo"), que vive en SU propia
                                      -- ubicacion (las 12 en meses_stock=1). Antes tomaba el meses_stock
                                      -- del SECTOR de la pieza (Bombilla=3, Plastico=4, Carton/Fleje=6),
                                      -- pensado para el stock de insumos del sector, e inflaba el
                                      -- sugerido: LLF8 a Alex daba 29 cajones (6.644 x 3 / 698) en vez
                                      -- de 9,5. El P.S. sigue tomando el del sector (como estaba).
                                      when e.tipo = 'tallerista'
                                        then ubic_de('tallerista', e.ref::bigint)
                                      else ubic_de('sector', ent.sector_id) end
                    limit 1), 1) as meses,
         case
           -- solo el fleje que se PESA va por kg/mes. IC3/IC3V (alambre N 90 cortado) son sector 5 pero
           -- se cuentan en unidades: no estan en v_consumo_fleje_kg y daban sugerido 0 a IJUPA
           -- [usuario 2026-09-25: "me aparece cero cajones en el sugerido. Tendria que salir el consumo"].
           when ent.sector_id = 5 and ent.unidad_medida = 'kg' then coalesce(fk.consumo_kg_mes, 0)
           when e.tipo = 'tallerista'     then coalesce(ct.uni_mes, 0)
           when e.tipo = 'proveedor_at'   then coalesce(cpa.uni_mes, 0)
           else                                coalesce(vc.consumo_uni_mes, 0)
         end as consumo
    ) cons
    cross join lateral (
       -- FASONERO: el techo es lo que falta entregar de su O.C., no el consumo x meses. Para el
       -- resto (PS normal y tallerista) no cambia nada.
       select case when e.tipo = 'proveedor_servicio'
                    and exists (select 1 from proveedor_servicio ps3
                                 where ps3.id = e.ref::bigint and ps3.pedido_por_oc)
                   then coalesce((select oc.pend from oc_ps oc
                                   where oc.proveedor_id = e.ref::bigint and oc.comp_id = e.comp_id), 0)
                   -- TALLERISTA CON O.C. DE VIRGILIO: mismo criterio que el fasonero sin O.C. — el
                   -- pedido no sale del consumo x meses sino de una orden que GP2 no lee, asi que
                   -- el techo es 0 y con el el sugerido [usuario 2026-09-23: "No es o.c. de
                   -- insumos. Es orden de compra que se hace desde Gestion Virgilio que hoy no
                   -- esta modelado aca. Por ahora sugeri 0"]. Cuando esa O.C. se modele, este 0
                   -- es lo unico que se cambia.
                   when e.tipo = 'tallerista'
                    and exists (select 1 from tallerista t8
                                 where t8.id = e.ref::bigint and t8.pedido_por_oc_virgilio)
                   -- (2026-09-26, unas horas: los pasos que entregan en GARAGE tambien iban por esta O.C.;
                   -- el dueno lo corrigio: "los que llenan garage se tienen que llenar por orden de compra
                   -- de INSUMOS, no por orden de compra de articulo terminado". Vuelven al maximo de la casa.)
                   -- 2026-09-26: la O.C. de Virgilio YA se lee (espejo GP2.oc_virgilio). El techo son las
                   -- partes que ese tallerista necesita para lo que falta entregar de la O.C. vigente,
                   -- explotada por receta y ruta (v_oc_virgilio_partes_tallerista). Sin O.C. sigue en 0.
                   then coalesce((select vt.uni_requeridas from v_oc_virgilio_partes_tallerista vt
                                   where vt.tallerista_id = e.ref::bigint and vt.componente_id = e.comp_id), 0)
                   -- PROV. DE ART. TERMINADO: igual que el tallerista con O.C. de Virgilio. El proveedor de
                   -- articulo terminado no tiene un maximo de inventario nuestro alla (no es gente de
                   -- la misma confianza que el tallerista a facon): lo que hay que mandarle sale de una
                   -- O.C. que emite Gestion Virgilio y que GP2 no lee, asi que el techo es 0 y con el el
                   -- sugerido [usuario 2026-09-24: "no tienen un maximo alla ellos... por lo tanto no
                   -- tiene que haber un sugerido de que mandarle, sino que tiene que aparecer en cero.
                   -- Cuando salga orden de compra de Virgilio... lo hace otro sistema ahora"]. DA VUELTA
                   -- la migracion del 2026-09-23 (consumo x meses con reparto), que queda dormida.
                   when e.tipo = 'proveedor_at'
                   -- ...HASTA EL 2026-09-26: ahora GP2 lee esa O.C. (espejo GP2.oc_virgilio ->
                   -- v_oc_virgilio_partes) y el techo son las PARTES (carton y caja) que el prov AT
                   -- necesita tener para cumplir lo que le falta entregar de su O.C. vigente
                   -- [usuario 2026-09-26: "solamente tenemos que mandarle partes para que puedan
                   -- hacer lo que les pide su orden de compra"]. Sin O.C. vigente sigue en 0.
                   then coalesce((select vp.uni_requeridas from v_oc_virgilio_partes vp
                                   where vp.tipo = 'proveedor_at' and vp.ref_id = e.ref::bigint
                                     and vp.componente_id = e.comp_id), 0)
                   else cons.consumo * cons.meses end as techo
    ) t
),
-- INYECTOR: el pedido de bolsas surge de la O.C. de partes plasticas ENVIADA (no del deficit
-- automatico). Sin OC enviada -> maximo(O.C.)=0 y sugerido=0; recien cuando se manda la OC de partes
-- (Compras/OC_GP2, proveedor = el inyector) aparecen los kg de bolsa. [usuario 2026-09-16]
rep_iny as (
  select 'inyector'::text as tipo, c.proveedor as ref, c.material_id as comp_id,
         sum(coalesce(ocp.pend,0) * coalesce(c.kg_x_uni,0)) as maximo_dest,  -- O.C. de partes -> kg de resina
         0::numeric as stock_dest,                                           -- el Stock lo pone online_sector en el front
         greatest(0, round(
            sum(coalesce(ocp.pend,0) * coalesce(c.kg_x_uni,0))
            - coalesce((select ir.cantidad from inventario ir
                         where ir.componente_id = c.material_id
                           and ir.ubicacion_id = ubic_de('inyector',
                                 (select pi2.id from proveedor_insumo pi2 where pi2.nombre = c.proveedor limit 1))
                         limit 1), 0)
         , 2)) as sugerido
    from componente c
    left join lateral (
       -- el vinculo es la PIEZA (c.proveedor ya es el inyector), no o.proveedor: la OC de rubro
       -- Plastico abarca partes de varios inyectores y puede venir con proveedor NULL.
       select sum(oi.cantidad - coalesce(oi.recibido,0)) as pend
         from orden_compra o
         join orden_compra_item oi on oi.oc_id = o.id
        where o.estado = 'enviada' and oi.componente_id = c.id
    ) ocp on true
   where c.material_id is not null and c.estado_compra is null and c.proveedor is not null
     and exists (select 1 from proveedor_insumo pi where pi.nombre = c.proveedor)
   group by c.proveedor, c.material_id
),
rec as (
  select 'tallerista'::text as tipo, v.ref_id::text as ref, v.comp_id,
         case when exists (select 1 from componente_bom b where b.componente_padre_id = v.comp_id)
              then null::bigint
              else (select case when count(distinct rp.comp_entrada_id) = 1
                                then min(rp.comp_entrada_id) end
                      from ruta_paso rp
                     where rp.tipo_paso = 'tallerista' and rp.tallerista_id = v.ref_id
                       and rp.comp_salida_id = v.comp_id and rp.comp_entrada_id is not null
                       and rp.comp_entrada_id <> v.comp_id) end as comp_entrada_id,
         (select count(distinct rp.comp_entrada_id) from ruta_paso rp
           where rp.tipo_paso = 'tallerista' and rp.tallerista_id = v.ref_id
             and rp.comp_salida_id = v.comp_id and rp.comp_entrada_id is not null
             and rp.comp_entrada_id <> v.comp_id)::int as n_entradas,
         exists (select 1 from componente_bom b where b.componente_padre_id = v.comp_id) as tiene_bom,
         null::text as cod_art,
         coalesce((select i.cantidad from inventario i
                    where i.componente_id = v.comp_id
                      and i.ubicacion_id = ubic_de('tallerista', v.ref_id) limit 1), 0) as esperado,
         'online_tall'::text as esperado_origen
    from v_contraparte_parte v
    join componente c on c.id = v.comp_id
   where v.tipo = 'tallerista' and v.lado = 'salida'
     and c.sector_id <> 12 and not coalesce(c.discontinuado,false)
     and exists (select 1 from tallerista t where t.id = v.ref_id and t.activo and t.id <> 3)
  union all
  select 'proveedor_servicio', rp.proveedor_id::text, rp.comp_salida_id, rp.comp_entrada_id,
         1, false, null::text,
         coalesce((select i.cantidad from inventario i
                    where i.componente_id = rp.comp_entrada_id
                      and i.ubicacion_id = ubic_de('proveedor_servicio', rp.proveedor_id) limit 1), 0),
         'online_ps'
    from (select distinct proveedor_id, comp_entrada_id, comp_salida_id
            from ruta_paso
           where tipo_paso = 'proveedor_servicio' and proveedor_id is not null
             and comp_entrada_id is not null and comp_salida_id is not null) rp
    join componente cs on cs.id = rp.comp_salida_id and not coalesce(cs.discontinuado,false)
  union all
  select 'proveedor_at', a.proveedor_at_id::text, null::bigint, null::bigint, 0, false, a.cod_art,
         (select sum(oi.cantidad - coalesce(oi.recibido,0)) from orden_compra o
            join orden_compra_item oi on oi.oc_id = o.id
            join componente ci on ci.id = oi.componente_id
           where o.estado in ('borrador','enviada')
             and o.proveedor = (select nombre from proveedor_at where id = a.proveedor_at_id)
             and ci.codigo = a.cod_art),
         'oc'
    from articulo_prov_at a
   where coalesce(a.activo,true)
     and exists (select 1 from proveedor_at p where p.id = a.proveedor_at_id and coalesce(p.activo,true))
     and not exists (select 1 from articulo art where art.codigo = a.cod_art and art.discontinuado)
  union all
  select 'proveedor_insumo', o.proveedor, oi.componente_id, null::bigint, 0, false, null::text,
         sum(oi.cantidad - coalesce(oi.recibido,0)),
         'oc'
    from orden_compra o
    join orden_compra_item oi on oi.oc_id = o.id
   where o.estado in ('borrador','enviada')
   group by o.proveedor, oi.componente_id
  having sum(oi.cantidad - coalesce(oi.recibido,0)) > 0
  union all
  select 'virgilio', 'virgilio', i.componente_id, null::bigint, 0, false, null::text,
         sum(i.cantidad), 'online_virgilio'
    from inventario i
    join ubicacion u on u.id = i.ubicacion_id and u.tipo in ('virgilio','virgilio_sector')
    join componente c on c.id = i.componente_id
   where c.sector_id <> 12 and not coalesce(c.discontinuado,false)
   group by i.componente_id
  having sum(i.cantidad) <> 0
  union all
  -- IMPORTADOS (2026-09-30): los TRAE Virgilio. Antes eran el rubro "Importados" de Recepcion de
  -- Insumos; ahora van sueltos en Recibir -> Virgilio [usuario: "que no esten dentro del modulo
  -- importados, que esten sueltos"]. Se registran como la recepcion de un Importado (remito en
  -- unidades y despues el control en kg).
  select 'virgilio', 'virgilio', c.id, null::bigint, 0, false, null::text, null::numeric, null::text
    from componente c
   where c.estado_compra = 'importado' and not coalesce(c.discontinuado,false)
),
env_x as (
  select distinct on (e.tipo, e.ref, e.comp_id) e.tipo, e.ref, e.comp_id,
         c.codigo cod,
         -- el terminado se llama como el ARTICULO ("Cierra Bolsa x2", no "058 Terminado")
         case when c.sector_id = 12
              then coalesce((select a.descripcion from articulo a where upper(a.codigo) = upper(c.codigo) limit 1), c.descripcion)
              else c.descripcion end descr,
         s.nombre sector, c.unidad_medida um,
         c.uni_x_cajon uxc, c.kg_x_uni kgu,
         -- envase de ENVIO propio de la pieza (componente.entrega_unidad/entrega_uni_x): una caja
         -- de 100 (GRJ13/GRJ14), una caja de 2400 (Descorazonador) o las bolsas de 120 de GRJ5/GRJ6.
         -- Si esta cargado gana sobre el "cajon" teorico (uni_x_cajon). [usuario 2026-09-24]
         c.entrega_unidad ent_uni, c.entrega_uni_x ent_ux,
         -- en que se escribe la CANTIDAD del envio: 'envase' (cajas cerradas) o 'kg'. NULL = la
         -- regla del sector (carton/caja en envase, el resto en kg). Z21: cajas [usuario 2026-09-25].
         c.envio_carga env_carga_pieza,
         c.sector_id sec_id, c.carton_formato cfmt,
         -- el terminado de Fabrica vive en "Art. Terminado (Fabrica)", no en un sector (2026-09-30)
         case when c.sector_id = 12
              then coalesce((select i.cantidad from inventario i
                              where i.componente_id = c.id
                                and i.ubicacion_id = ubic_de('art_terminado', 3) limit 1), 0)
              else coalesce((select i.cantidad from inventario i
                              where i.componente_id = c.id
                                and i.ubicacion_id = ubic_de('sector', c.sector_id) limit 1), 0) end online_sector,
         (select f.uxc from fab f where f.comp_id = c.id limit 1) art_uxc,
         case when e.tipo = 'virgilio' then case c.sector_id when 12 then 'Art. Terminados'
                                                             when 1 then 'SC' when 2 then 'SP'
                                                             else 'Insumos' end end grupo,
         -- AVISO A VIRGILIO (D4): lo que todavia espera el Si de Virgilio y lo que Virgilio
         -- DENEGO en los ultimos 15 dias (ya volvio al stock de aca) [regla general: se ve donde se cargo]
         case when e.tipo = 'virgilio' then (select sum(ev.cantidad) from envio_virgilio ev
                                              where ev.componente_id = c.id and ev.estado = 'pendiente') end vir_pend,
         case when e.tipo = 'virgilio' then (select jsonb_build_object('cantidad', sum(ev.cantidad),
                                                      'motivo', string_agg(distinct ev.denegado_motivo, ' · '),
                                                      'ult', max(ev.denegado_en))
                                               from envio_virgilio ev
                                              where ev.componente_id = c.id and ev.estado = 'denegado'
                                                and ev.denegado_en > now() - interval '15 days'
                                             having count(*) > 0) end vir_deneg,
         -- saldo en poder del tercero = lo que le enviamos − lo que nos entregó = inventario de lo
         -- que se le manda (la pieza/resina) en la ubicacion del destino. [usuario 2026-09-16]
         coalesce((select i.cantidad from inventario i
                    where i.componente_id = c.id
                      and i.ubicacion_id = (case
                            when e.tipo in ('proveedor_servicio','tallerista','proveedor_at') then ubic_de(e.tipo, e.ref::bigint)
                            when e.tipo = 'inyector' then ubic_de('inyector',
                                  (select pi3.id from proveedor_insumo pi3 where pi3.nombre = e.ref limit 1))
                          end) limit 1), 0) saldo_dest,
         coalesce(rep.maximo_dest, ri.maximo_dest) maximo_dest,
         coalesce(rep.stock_dest,  ri.stock_dest)  stock_dest,
         coalesce(rep.sugerido,    ri.sugerido)    sugerido
    from env e
    join componente c on c.id = e.comp_id and not coalesce(c.discontinuado,false)
                     and c.id not in (select comp_id from "GP2".v_componente_muerto)
    left join sector s on s.id = c.sector_id
    left join rep     on rep.tipo = e.tipo and rep.ref = e.ref and rep.comp_id = e.comp_id
    left join rep_iny ri on ri.tipo = e.tipo and ri.ref = e.ref and ri.comp_id = e.comp_id
   order by e.tipo, e.ref, e.comp_id
),
rec_x as (
  select r.tipo, r.ref, r.comp_id, r.comp_entrada_id, r.n_entradas, r.tiene_bom, r.cod_art,
         max(r.esperado) esperado, min(r.esperado_origen) esperado_origen,
         coalesce(c.codigo, r.cod_art) cod,
         coalesce(c.descripcion, (select max(descripcion) from articulo_prov_at ap
                                   where ap.cod_art = r.cod_art)) descr,
         s.nombre sector, c.unidad_medida um, c.uni_x_cajon uxc, c.kg_x_uni kgu,
         c.entrega_unidad ent_uni, c.entrega_uni_x ent_ux, c.remito_unidad remito_uni,
         ce.codigo ent_cod, ce.descripcion ent_desc,
         -- el CAJON DE LA PIEZA ENVIADA, SOLO donde la pieza vuelve en el MISMO cajon en el que se
         -- mando: hoy los REMACHES que niquela Guazzaroni (sector 8). El esperado de un P.S. se
         -- cuenta en unidades de la ENTRADA (es lo que el proveedor tiene en su poder), asi que ahi
         -- el envase con el que se mira tiene que ser el de ESA pieza y no el de la que devuelve
         -- [usuario 2026-09-18: "Guazzaroni nos entrega los remaches niquelados en los mismos
         -- cajones que se lo enviamos... si envio 2 cajones lo esperado es recibir 2 cajones aprox
         -- (el peso niquelado es un poquito mas - muy infima la diferencia)", y enseguida el limite:
         -- "no aplica para todos los casos... te lo estoy diciendo en el caso de los remaches"].
         -- El uni_x_cajon del remache niquelado (V11 = 2.729 uni = 2 kg) NO es un cajon: es la bolsa
         -- en la que se fracciona DESPUES de recibirlo, con la matriz de embolsado. Mirar el
         -- esperado con ese numero multiplicaba por 10 lo que se le habia mandado.
         -- NULL en el resto de los P.S.: ahi el front sigue con el cajon de la pieza devuelta.
         case when ce.sector_id = 8 then ce.uni_x_cajon end ent_uxc,
         case when ce.sector_id = 8 then ce.kg_x_uni    end ent_kgu,
         -- ...Y CUANTO MIDE ESE CAJON DE VERDAD (2026-09-21): el que anoto logistica al enviar
         -- (movimiento.cajones), no el uni_x_cajon del maestro. CV1 salio como 1 cajon de 21 kg
         -- contra un cajon teorico de 20 kg y la tarjeta de Recibir decia 1,05 cajones [usuario:
         -- "tiene que aparecer en su stock los cajones que escribe logistica, no los que se
         -- calcula a partir de los kg"]. Va SOLO donde ya va ent_uxc (P.S. y sector Remache), que
         -- es donde el front mira el envase de la pieza ENVIADA; null = nadie anoto cajones y
         -- queda el de siempre.
         max(case when ce.sector_id = 8 and r.tipo = 'proveedor_servicio'
                  then (select v.uni_x_cajon_anotado from v_caj_contraparte v
                         where v.componente_id = r.comp_entrada_id
                           and v.ubicacion_id = ubic_de(r.tipo, r.ref::bigint)) end) ent_uxc_anot,
         (select a.articulos_por_caja from articulo a where a.codigo = r.cod_art) por_caja,
         (c.estado_compra = 'importado') importado, c.sector_id sec_id, c.proveedor prov
    from rec r
    left join componente c on c.id = r.comp_id
    left join componente ce on ce.id = r.comp_entrada_id
    left join sector s on s.id = c.sector_id
   where (r.comp_id is null or not coalesce(c.discontinuado,false))
     and (r.comp_id is null or r.comp_id not in (select comp_id from "GP2".v_componente_muerto))
   group by r.tipo, r.ref, r.comp_id, r.comp_entrada_id, r.n_entradas, r.tiene_bom, r.cod_art,
            c.codigo, c.descripcion, s.nombre, c.unidad_medida, c.uni_x_cajon, c.kg_x_uni,
            c.entrega_unidad, c.entrega_uni_x, c.remito_unidad,
            ce.codigo, ce.descripcion, ce.uni_x_cajon, ce.kg_x_uni, ce.sector_id,
            c.estado_compra, c.sector_id, c.proveedor
),
-- envio_unidad / envio_uni_x / envio_carga_unidad: unidad de ENVIO por proveedor (display), p.ej. AJ
-- Adhesivos manda de a paquetes de 100 pliegos y Ester de a bolsas de 1800 mangos. Es solo
-- presentacion: el front muestra/precarga el sugerido dividido por envio_uni_x (techo) y rotula la
-- columna con envio_unidad. envio_carga_unidad dice en QUE unidad se escribe la CANTIDAD: null = en
-- la unidad de envio (AJ escribe paquetes y el front multiplica de nuevo), 'kg' = se escribe en kg y
-- al lado se muestran las bolsas (Ester). En los dos casos lo que llega a la base esta en unidad
-- canonica (uni/kg): el inventario nunca ve bolsas ni paquetes. Hoy solo lo tiene
-- proveedor_servicio; el resto va null. [usuario 2026-09-17]
cp as (
  select 'tallerista'::text tipo, t.id::text ref, t.nombre, null::text envio_unidad, null::numeric envio_uni_x, null::text envio_carga_unidad, null::text entrega_unidad, null::numeric entrega_uni_x
    from tallerista t
   where t.activo
     and exists (select 1 from v_contraparte_parte v where v.tipo='tallerista' and v.ref_id = t.id)
  union all
  select 'proveedor_servicio', ps.id::text, ps.nombre, ps.envio_unidad, ps.envio_uni_x, ps.envio_carga_unidad, ps.entrega_unidad, ps.entrega_uni_x
    from proveedor_servicio ps
   where exists (select 1 from v_contraparte_parte v where v.tipo='proveedor_servicio' and v.ref_id = ps.id)
  union all
  select 'proveedor_at', p.id::text, p.nombre, null::text, null::numeric, null::text, null::text, null::numeric
    from proveedor_at p where coalesce(p.activo,true)
  union all
  select distinct 'proveedor_insumo', o.proveedor, o.proveedor, null::text, null::numeric, null::text, null::text, null::numeric
    from orden_compra o where o.estado in ('borrador','enviada')
  union all
  select 'virgilio', 'virgilio', 'Virgilio', null::text, null::numeric, null::text, null::text, null::numeric
  union all
  select distinct 'inyector', c.proveedor, c.proveedor, null::text, null::numeric, null::text, null::text, null::numeric
    from componente c
   where c.material_id is not null and c.estado_compra is null and c.proveedor is not null
     and exists (select 1 from proveedor_insumo pi where pi.nombre = c.proveedor)
)
select jsonb_build_object(
  'generado_en', now(),
  'contrapartes', (
    select coalesce(jsonb_agg(jsonb_build_object(
             'tipo', cp.tipo, 'ref', cp.ref, 'nombre', cp.nombre,
             -- O.C. DE GESTION VIRGILIO (2026-09-23): a este tallerista no se le manda contra el
             -- maximo de la casa; lo que tiene que hacer sale de una O.C. que emite Gestion
             -- Virgilio y que GP2 todavia no lee. La Tablet lo muestra en su propia baldosa
             -- ("Talleristas O.C.", solo en Enviar) y su sugerido es 0 (ver la CTE t) [usuario].
             'oc', (cp.tipo = 'tallerista' and exists (select 1 from tallerista t9
                      where t9.id = cp.ref::bigint and t9.pedido_por_oc_virgilio)),
             'envio_unidad', cp.envio_unidad, 'envio_uni_x', cp.envio_uni_x,
             'entrega_unidad', cp.entrega_unidad, 'entrega_uni_x', cp.entrega_uni_x,
             'envio_carga_unidad', cp.envio_carga_unidad,
             'n_env', (select count(*) from env_x e where e.tipo = cp.tipo and e.ref = cp.ref),
             'n_rec', (select count(*) from rec_x r where r.tipo = cp.tipo and r.ref = cp.ref)
           ) order by cp.nombre), '[]'::jsonb)
      from cp where cp.nombre is not null),
  'enviar', (
    select coalesce(jsonb_agg(jsonb_build_object(
             'tipo', tipo, 'ref', ref, 'comp_id', comp_id, 'cod', cod, 'desc', descr,
             'sector', sector, 'um', um, 'uxc', uxc, 'kg_x_uni', kgu,
             -- el TERMINADO de Fabrica se carga en CAJAS (articulo.articulos_por_caja) [2026-09-30]
             'env_unidad', case when sec_id = 12 and art_uxc > 0 and tipo in ('tallerista','virgilio') then 'cajas'
                                when tipo in ('tallerista','proveedor_at')
                                  then case when sec_id in (10,11) then coalesce(nullif(btrim(ent_uni),''), 'paquetes')
                                            else coalesce(nullif(btrim(ent_uni),''), 'cajones') end end,
             'env_factor', case when sec_id = 12 and art_uxc > 0 and tipo in ('tallerista','virgilio') then art_uxc
                                when tipo in ('tallerista','proveedor_at') then case
                                  when sec_id = 10 then nullif(ent_ux,0)
                                  when sec_id = 11 then (select pa.valor::numeric from parametro pa
                                                          where pa.clave = 'caja_uni_x_paquete')
                                  else coalesce(nullif(ent_ux,0), uxc) end end,
             'env_carga',  case when sec_id = 12 and art_uxc > 0 and tipo in ('tallerista','virgilio') then 'envase'
                                when tipo in ('tallerista','proveedor_at')
                                  then coalesce(env_carga_pieza,
                                         case when sec_id in (10,11) then 'envase' else 'kg' end) end,
             'online_sector', online_sector, 'saldo_dest', saldo_dest, 'grupo', grupo, 'sec_id', sec_id,
             'vir_pend', vir_pend, 'vir_deneg', vir_deneg,
             'maximo', maximo_dest, 'stock_dest', stock_dest, 'sugerido', sugerido
           ) order by cod), '[]'::jsonb) from env_x),
  'recibir', (
    select coalesce(jsonb_agg(jsonb_build_object(
             'tipo', tipo, 'ref', ref, 'comp_id', comp_id, 'comp_entrada_id', comp_entrada_id,
             'n_entradas', n_entradas, 'tiene_bom', tiene_bom,
             'cod_art', cod_art, 'cod', cod, 'desc', descr, 'sector', sector, 'um', um,
             'uxc', uxc, 'kg_x_uni', kgu, 'por_caja', por_caja,
             -- LA UNIDAD DEL REMITO LA DICE LA PIEZA (componente.remito_unidad): las bombillas de
             -- Martin vienen contadas y la cuchilla pesada [usuario 2026-09-23]. Sin dato, la
             -- Tablet usa la unidad canonica.
             'remito_unidad', remito_uni,
             -- envase de ENTREGA (hoy solo el tallerista): el esperado se mira en cajones (o en las
             -- bolsas de 120 de GRJ5/GRJ6) y la cantidad se escribe en kg.
             'env_unidad', case when tipo = 'tallerista' then coalesce(ent_uni, 'cajones')
                                -- IMPORTADO con el remito en envases (C13 en cajas de 144) [2026-09-25]
                                when tipo = 'virgilio' and importado and lower(coalesce(remito_uni,'')) = 'envase'
                                     and ent_ux > 0 then coalesce(ent_uni, 'envases') end,
             'env_factor', case when tipo = 'tallerista' then coalesce(ent_ux, uxc)
                                when tipo = 'virgilio' and importado and lower(coalesce(remito_uni,'')) = 'envase'
                                     and ent_ux > 0 then ent_ux end,
             'env_carga',  case when tipo = 'tallerista' then 'kg' end,
             'ent_cod', ent_cod, 'ent_desc', ent_desc, 'ent_uxc_anot', ent_uxc_anot,
             'ent_uxc', ent_uxc, 'ent_kgu', ent_kgu,
             'esperado', esperado, 'esperado_origen', esperado_origen,
             'importado', coalesce(importado, false), 'sector_id', sec_id, 'proveedor', prov
           ) order by cod), '[]'::jsonb) from rec_x),
  'alertas_abiertas', (select count(*) from alerta_recepcion where estado = 'abierta')
);
$function$
;

-- ---------- 5) el espejo no descuenta dos veces el despiece de Fábrica ----------
CREATE OR REPLACE FUNCTION "GP2".fn_entregas_virgilio_espejo()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'GP2'
AS $function$
declare
  v_nom  text := upper(btrim(coalesce(NEW."Nombre_Tall",'')));
  v_tipo text; v_ref bigint;
  v_art record; v_uni numeric; v_fecha timestamptz;
begin
  begin
    if coalesce(btrim(NEW."Cod"),'') = '' then return NEW; end if;

    begin v_fecha := nullif(btrim(coalesce(NEW."Fecha",'')),'')::timestamptz;
    exception when others then v_fecha := null; end;
    v_fecha := coalesce(v_fecha, now());

    select a.tipo, a.ref_id into v_tipo, v_ref from contraparte_alias a where a.alias = v_nom;
    if v_tipo is null then
      select 'tallerista', t.id into v_tipo, v_ref from tallerista t
       where upper(t.nombre)=v_nom or upper(t.nombre) ~ ('(^|\s)'||v_nom||'($|\s)') limit 1;
    end if;
    if v_tipo is null then
      select 'proveedor_at', p.id into v_tipo, v_ref from proveedor_at p where upper(p.nombre)=v_nom limit 1;
    end if;
    if v_tipo is null then
      insert into virgilio_espejo_pend(entrega_id,fecha,nombre_tall,cod,cajas,motivo)
      values (NEW.id, NEW."Fecha", NEW."Nombre_Tall", NEW."Cod", NEW."Cajas", 'contraparte sin resolver');
      return NEW;
    end if;
    -- FABRICA (interno, LOG/ FABR) desde 2026-09-30: el despiece lo descuenta "Producir en Fabrica" de
    -- la tablet (fabrica_producir) y el terminado sale con Enviar -> Virgilio. Si el espejo lo
    -- descontara otra vez cuando Virgilio recibe, el despiece saldria DOS veces. (El trigger esta
    -- apagado; esto es para el dia que se prenda.)
    if v_tipo = 'interno' then return NEW; end if;

    -- articulo: exacto primero, despues sin ceros de adelante en ambos lados
    select a.id, a.articulos_por_caja into v_art from articulo a
     where a.codigo = btrim(NEW."Cod")
        or regexp_replace(a.codigo,'^0+','') = regexp_replace(btrim(NEW."Cod"),'^0+','')
     order by (a.codigo = btrim(NEW."Cod")) desc limit 1;
    if v_art.id is null then
      insert into virgilio_espejo_pend(entrega_id,fecha,nombre_tall,cod,cajas,motivo)
      values (NEW.id, NEW."Fecha", NEW."Nombre_Tall", NEW."Cod", NEW."Cajas", 'articulo sin equivalente en GP2');
      return NEW;
    end if;

    v_uni := coalesce(NEW."Cajas",0) * coalesce(v_art.articulos_por_caja,0);
    if v_uni <= 0 then
      insert into virgilio_espejo_pend(entrega_id,fecha,nombre_tall,cod,cajas,motivo)
      values (NEW.id, NEW."Fecha", NEW."Nombre_Tall", NEW."Cod", NEW."Cajas", 'cantidad en cero');
      return NEW;
    end if;

    perform "GP2".recepcion_virgilio(jsonb_build_object(
      'fecha', v_fecha, 'origen_tipo', v_tipo, 'origen_id', v_ref,
      'remito', NEW."Remito",
      'items', jsonb_build_array(jsonb_build_object('articulo_id', v_art.id, 'cantidad', v_uni))));
  exception when others then
    insert into virgilio_espejo_pend(entrega_id,fecha,nombre_tall,cod,cajas,motivo)
    values (NEW.id, NEW."Fecha", NEW."Nombre_Tall", NEW."Cod", NEW."Cajas", 'error: '||sqlerrm);
  end;
  return NEW;
end $function$
;

-- ---------- 6) gv_cod: el código de Gestión Virgilio con que se recibió (memoria para el próximo envío) ----------
-- Lo escribe public.gv_envio_cervantes_confirmar. Para un insumo / SC / SP sin vínculo en
-- importado_virgilio_componente, Virgilio lo recibe con un código temporal (TMP-…) o el que
-- elija: la próxima vez que Cervantes mande la MISMA pieza, el aviso ya propone ese código
-- (si todavía existe en public."Insumos"). No se adivina: es el que alguien eligió al recibir.
alter table "GP2".envio_virgilio add column if not exists gv_cod text;
comment on column "GP2".envio_virgilio.gv_cod is
  'Código de Gestión Virgilio con que se recibió (artículo o insumo). Lo escribe gv_envio_cervantes_confirmar.';
