-- =====================================================================
-- O.C.: la columna "Recibido" muestra lo que REALMENTE entro (2026-10-05)
--
-- [usuario 2026-10-05, textual: "Recibi mas de 1250 cuchillos de untar blanco. Quiero que me ponga
--  lo que realmente recibi" / "En principio siempre queda lo del control pero despues con la
--  validacion puede cambiar"]
--
-- Caso real: OC N° 2 (JL Matriceria). PEP9 pedido 1.250, remito 1.300, control 1.342 -> la OC decia
-- 1.250. PC4 pedido 2.800, control 2.806 -> la OC decia 2.800. El stock ya tenia 1.342 y 2.806.
--
-- Dos agujeros:
--  1) _aplicar_recepcion_a_oc topeaba lo aplicado en lo pedido (least(cant, pendiente)) y el
--     excedente se perdia: la OC nunca podia mostrar mas de lo pedido.
--  2) El cruce se hacia UNA vez, con lo tipeado al cargar el remito. El control (cajas, kg, cartones),
--     el traslado a Virgilio, la validacion Remito vs Control y anular_recepcion cambian (o borran)
--     movimiento.cantidad, y la OC no se enteraba.
--
-- Arreglo:
--  - GP2.oc_item_recepcion: que movimiento cruzo contra que renglon de OC y cuanto (en la unidad
--    del renglon). Lo escribe _aplicar_recepcion_a_oc_mov cuando el que llama le pasa el movimiento.
--  - El excedente (lo recibido de mas, cuando ya no queda renglon abierto) va al ultimo renglon
--    que toco esa recepcion: "Recibido" puede pasar a "Pedido".
--  - Trigger AFTER UPDATE/DELETE en GP2.movimiento: cada cambio de la cantidad recibida (compra:
--    cantidad; entrega_ps de fasonero: cantidad_transformada) se lleva a los renglones cruzados.
--    Sube -> al ultimo renglon. Baja -> del ultimo para atras, sin bajar de 0. Borrado -> se
--    devuelve todo y el cruce queda en 0 (no se borra). La OC se completa sola (misma regla de
--    siempre) pero NUNCA se reabre sola:
--    oc_marcar permite cerrar a mano una OC parcial y eso no se pisa.
--  - Los pendientes que sumaban (cantidad - recibido) con signo (oc_bundle, tablet_bundle) pasan a
--    greatest(..., 0) por renglon: un renglon con excedente no le come el pendiente a otro.
-- =====================================================================

-- ---------- 1) tabla de cruce ----------
create table if not exists "GP2".oc_item_recepcion (
  id bigint generated by default as identity primary key,
  oc_item_id bigint not null references "GP2".orden_compra_item(id) on delete cascade,
  -- sin FK a movimiento a proposito: el trigger AFTER DELETE de movimiento necesita leer estas
  -- filas, y un ON DELETE CASCADE las borraria antes (los triggers RI corren primero).
  movimiento_id bigint not null,
  cantidad numeric not null,
  creado_en timestamptz not null default now()
);
create index if not exists oc_item_recepcion_mov_idx on "GP2".oc_item_recepcion(movimiento_id);
create index if not exists oc_item_recepcion_item_idx on "GP2".oc_item_recepcion(oc_item_id);
alter table "GP2".oc_item_recepcion enable row level security;
-- lectura como el resto de GP2 (verificar.sql regla D); la escritura va solo por las funciones
create policy p_gp2_select on "GP2".oc_item_recepcion for select to anon, authenticated using (true);
comment on table "GP2".oc_item_recepcion is
  'Cruce recepcion -> renglon de O.C.: cuanto de cada movimiento (compra / entrega_ps de fasonero) se aplico a cada orden_compra_item, en la unidad del renglon. Lo escribe _aplicar_recepcion_a_oc_mov y lo mantiene fn_movimiento_oc_recibido (control, validacion, anular). 2026-10-05.';

-- ---------- 2) conversion kg <-> uni ----------
create or replace function "GP2"._oc_convertir(p_cant numeric, p_de text, p_a text, p_kg_x_uni numeric)
 returns numeric
 language sql
 immutable
as $function$
  -- Todo lo que no es 'kg' es unidad (mismo criterio que _aplicar_recepcion_a_oc).
  select case
    when (lower(coalesce(p_de,'uni')) = 'kg') = (lower(coalesce(p_a,'uni')) = 'kg') then p_cant
    when p_kg_x_uni is null or p_kg_x_uni <= 0 then null
    when lower(coalesce(p_a,'uni')) = 'kg' then p_cant * p_kg_x_uni   -- uni -> kg
    else p_cant / p_kg_x_uni                                          -- kg -> uni
  end
$function$;

-- ---------- 3) _aplicar_recepcion_a_oc_mov: excedente + cruce ----------
-- Funcion nueva (no se cambia la firma de la vieja: el conector de Supabase no deja hacer DROP sin
-- confirmacion, y una sobrecarga con default dejaria las llamadas de 4 argumentos ambiguas).
create or replace function "GP2"._aplicar_recepcion_a_oc_mov(p_comp_id bigint, p_cantidad numeric, p_unidad text, p_proveedor text, p_mov_id bigint)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'GP2'
AS $function$
declare
  it record; v_resto numeric := p_cantidad; v_aplicar numeric; v_pend numeric;
  v_kgu numeric; v_cant_item numeric; v_ocs jsonb := '[]'::jsonb;
  v_prov text := nullif(btrim(coalesce(p_proveedor,'')),'');
  v_ult_id bigint; v_ult_unidad text; v_ult_num integer; v_exc numeric;
begin
  select kg_x_uni into v_kgu from componente where id = p_comp_id;
  for it in
    select oi.id, oi.cantidad, oi.recibido, oi.unidad, o.id oc_id, o.numero, o.estado
    from orden_compra_item oi
    join orden_compra o on o.id = oi.oc_id
    where oi.componente_id = p_comp_id
      and o.estado in ('enviada','borrador')
      and oi.recibido < oi.cantidad
    order by case when v_prov is not null and o.proveedor = v_prov then 0 else 1 end,
             case o.estado when 'enviada' then 0 else 1 end, o.numero, oi.id
  loop
    exit when v_resto <= 0;
    -- convertir lo recibido a la unidad del item de OC si difieren
    v_cant_item := v_resto;
    if lower(coalesce(it.unidad,'uni')) <> lower(coalesce(p_unidad,'uni')) then
      if v_kgu is null or v_kgu <= 0 then
        continue; -- sin conversion posible: no cruzar contra este item
      elsif lower(coalesce(it.unidad,'uni')) = 'kg' then
        v_cant_item := v_resto * v_kgu;      -- recibi uni, la OC pide kg
      else
        v_cant_item := v_resto / v_kgu;      -- recibi kg, la OC pide uni
      end if;
    end if;
    v_pend := it.cantidad - it.recibido;
    v_aplicar := least(v_cant_item, v_pend);
    if v_aplicar <= 0 then continue; end if;
    update orden_compra_item set recibido = recibido + v_aplicar where id = it.id;
    -- cruce: deja anotado que este movimiento entro por este renglon (lo usa el trigger de
    -- movimiento cuando el control / la validacion / anular cambian lo recibido)
    if p_mov_id is not null then
      insert into oc_item_recepcion(oc_item_id, movimiento_id, cantidad) values (it.id, p_mov_id, v_aplicar);
    end if;
    v_ult_id := it.id; v_ult_unidad := it.unidad; v_ult_num := it.numero;
    -- descontar del resto en la unidad de la recepcion
    if lower(coalesce(it.unidad,'uni')) <> lower(coalesce(p_unidad,'uni')) then
      if lower(coalesce(it.unidad,'uni')) = 'kg' then v_resto := v_resto - v_aplicar / v_kgu;
      else v_resto := v_resto - v_aplicar * v_kgu; end if;
    else
      v_resto := v_resto - v_aplicar;
    end if;
    v_ocs := v_ocs || jsonb_build_object('numero', it.numero, 'aplicado', round(v_aplicar,2), 'unidad', it.unidad);
    -- OC completa -> recibida
    if not exists (select 1 from orden_compra_item x where x.oc_id = it.oc_id and x.recibido < x.cantidad) then
      update orden_compra set estado = 'recibida' where id = it.oc_id and estado <> 'anulada';
      v_ocs := v_ocs || jsonb_build_object('numero', it.numero, 'completa', true);
    end if;
  end loop;
  -- EXCEDENTE (2026-10-05): entro mas de lo que quedaba pedido. Antes se tiraba (la OC no podia
  -- pasar de lo pedido); ahora va al ultimo renglon que toco esta recepcion, para que "Recibido"
  -- diga lo que entro de verdad [usuario: "quiero que me ponga lo que realmente recibi"].
  if v_ult_id is not null and round(v_resto, 6) > 0 then
    v_exc := _oc_convertir(v_resto, p_unidad, v_ult_unidad, v_kgu);
    if v_exc is not null and v_exc > 0 then
      update orden_compra_item set recibido = recibido + v_exc where id = v_ult_id;
      if p_mov_id is not null then
        update oc_item_recepcion set cantidad = cantidad + v_exc
         where id = (select max(x.id) from oc_item_recepcion x where x.movimiento_id = p_mov_id and x.oc_item_id = v_ult_id);
      end if;
      v_ocs := v_ocs || jsonb_build_object('numero', v_ult_num, 'excedente', round(v_exc,2), 'unidad', v_ult_unidad);
    end if;
  end if;
  return v_ocs;
end $function$;
revoke all on function "GP2"._aplicar_recepcion_a_oc_mov(bigint, numeric, text, text, bigint) from public, anon, authenticated;

-- la vieja queda como envoltorio: quien todavia la llame igual gana el excedente (sin cruce)
create or replace function "GP2"._aplicar_recepcion_a_oc(p_comp_id bigint, p_cantidad numeric, p_unidad text, p_proveedor text DEFAULT NULL::text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'GP2'
AS $function$
begin
  -- 2026-10-05: el cuerpo vive en _aplicar_recepcion_a_oc_mov (excedente + cruce por movimiento)
  return _aplicar_recepcion_a_oc_mov(p_comp_id, p_cantidad, p_unidad, p_proveedor, null);
end $function$;

-- ---------- 4) trigger: la OC sigue al ingreso real ----------
create or replace function "GP2".fn_movimiento_oc_recibido()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'GP2'
AS $function$
-- La O.C. sigue al INGRESO REAL de cada recepcion cruzada (2026-10-05) [usuario: "En principio
-- siempre queda lo del control pero despues con la validacion puede cambiar"]. El control, la
-- validacion Remito vs Control, el traslado a Virgilio y anular_recepcion terminan todos en
-- movimiento.cantidad (o en cantidad_transformada en la entrega del fasonero): por eso se mira aca
-- y no en cada una de esas funciones. Solo actua sobre movimientos con cruce en oc_item_recepcion.
declare
  v_old numeric; v_new numeric; v_delta numeric; v_u text; v_kgu numeric;
  l record; v_d numeric; v_q numeric; v_oc bigint;
begin
  if tg_op = 'DELETE' then
    -- se anulo la recepcion: se devuelve todo lo que habia entrado por cada renglon. El cruce no
    -- se borra: queda en 0 como rastro (la auditoria no se borra).
    for l in select x.oc_item_id, sum(x.cantidad) cant from oc_item_recepcion x
              where x.movimiento_id = old.id group by x.oc_item_id loop
      update orden_compra_item set recibido = greatest(recibido - l.cant, 0) where id = l.oc_item_id;
    end loop;
    update oc_item_recepcion set cantidad = 0 where movimiento_id = old.id;
    return old;
  end if;

  if not exists (select 1 from oc_item_recepcion where movimiento_id = new.id) then return new; end if;
  if new.tipo_mov = 'entrega_ps' then
    -- fasonero con O.C.: lo recibido es la pieza procesada (crear_entrega_ps / controlar_entrega)
    v_old := coalesce(old.cantidad_transformada, old.cantidad);
    v_new := coalesce(new.cantidad_transformada, new.cantidad);
    v_u   := new.unidad_destino;
    select kg_x_uni into v_kgu from componente where id = coalesce(new.comp_transformado_id, new.comp_id);
  else
    v_old := old.cantidad; v_new := new.cantidad; v_u := new.unidad_origen;
    select kg_x_uni into v_kgu from componente where id = new.comp_id;
  end if;
  v_delta := v_new - v_old;
  if v_delta is null or v_delta = 0 then return new; end if;

  if v_delta > 0 then
    -- entro mas: al ultimo renglon que toco esta recepcion (donde termino de entrar)
    select x.id, x.oc_item_id, oi.unidad, oi.oc_id into l
      from oc_item_recepcion x join orden_compra_item oi on oi.id = x.oc_item_id
     where x.movimiento_id = new.id order by x.id desc limit 1;
    v_d := _oc_convertir(v_delta, v_u, l.unidad, v_kgu);
    if v_d is null then return new; end if;
    update orden_compra_item set recibido = recibido + v_d where id = l.oc_item_id;
    update oc_item_recepcion set cantidad = cantidad + v_d where id = l.id;
    -- se completa sola, igual que en _aplicar_recepcion_a_oc
    update orden_compra o set estado = 'recibida'
     where o.id = l.oc_id and o.estado in ('enviada','borrador')
       and not exists (select 1 from orden_compra_item x where x.oc_id = o.id and x.recibido < x.cantidad);
  else
    -- entro menos: se descuenta del ultimo renglon para atras, sin bajar de 0. La OC NO se reabre
    -- sola (oc_marcar deja cerrar a mano una OC parcial; eso no se pisa).
    v_q := -v_delta;  -- en la unidad del movimiento
    for l in select x.id, x.oc_item_id, x.cantidad, oi.unidad
               from oc_item_recepcion x join orden_compra_item oi on oi.id = x.oc_item_id
              where x.movimiento_id = new.id and x.cantidad > 0 order by x.id desc loop
      exit when round(v_q, 6) <= 0;
      v_d := least(_oc_convertir(v_q, v_u, l.unidad, v_kgu), l.cantidad);
      if v_d is null or v_d <= 0 then continue; end if;
      update orden_compra_item set recibido = greatest(recibido - v_d, 0) where id = l.oc_item_id;
      update oc_item_recepcion set cantidad = cantidad - v_d where id = l.id;
      v_q := v_q - _oc_convertir(v_d, l.unidad, v_u, v_kgu);
    end loop;
  end if;
  return new;
end $function$;

create or replace trigger trg_movimiento_oc_recibido
  after update of cantidad, cantidad_transformada or delete on "GP2".movimiento
  for each row when (old.tipo_mov in ('compra','entrega_ps'))
  execute function "GP2".fn_movimiento_oc_recibido();
revoke all on function "GP2".fn_movimiento_oc_recibido() from public, anon, authenticated;
revoke all on function "GP2"._oc_convertir(numeric, text, text, numeric) from public, anon, authenticated;

-- ---------- 5) los que cruzan contra la OC pasan su movimiento ----------
do $$
declare
  r record; d text; n int;
begin
  for r in select * from (values
    ('"GP2".cargar_compra_mp',         $a$perform _aplicar_recepcion_a_oc(v_comp, p_kg, 'kg');$a$,
                                       $a$perform _aplicar_recepcion_a_oc_mov(v_comp, p_kg, 'kg', null, v_mov);$a$),
    ('"GP2".cargar_recepcion_charcas', $a$perform "GP2"._aplicar_recepcion_a_oc(p_comp_id, p_kg_balanza, 'kg');$a$,
                                       $a$perform "GP2"._aplicar_recepcion_a_oc_mov(p_comp_id, p_kg_balanza, 'kg', null, v_mov_prod);$a$),
    ('"GP2".cargar_recepcion_eclipse', $a$perform "GP2"._aplicar_recepcion_a_oc(p_comp_id, v_kg_producto, 'kg');$a$,
                                       $a$perform "GP2"._aplicar_recepcion_a_oc_mov(p_comp_id, v_kg_producto, 'kg', null, v_mov_prod);$a$),
    ('"GP2".crear_entrega_ps',         $a$v_oc := "GP2"._aplicar_recepcion_a_oc(p_comp_sp_id, p_kg, v_u, v_prov_sp);$a$,
                                       $a$v_oc := "GP2"._aplicar_recepcion_a_oc_mov(p_comp_sp_id, p_kg, v_u, v_prov_sp, v_id);$a$),
    ('"GP2".crear_recepcion_insumo',   $a$v_oc := "GP2"._aplicar_recepcion_a_oc(p_comp_id, p_cantidad, v_u, p_proveedor);$a$,
                                       $a$v_oc := "GP2"._aplicar_recepcion_a_oc_mov(p_comp_id, p_cantidad, v_u, p_proveedor, v_movid);$a$)
  ) t(fn, viejo, nuevo) loop
    select pg_get_functiondef(p.oid) into d
      from pg_proc p where p.oid = (select min(oid) from pg_proc where pronamespace = '"GP2"'::regnamespace
                                     and proname = replace(split_part(r.fn, '.', 2), '"', ''));
    n := (length(d) - length(replace(d, r.viejo, ''))) / length(r.viejo);
    if n <> 1 then raise exception '%: se esperaba 1 llamada a reemplazar y hay %', r.fn, n; end if;
    execute replace(d, r.viejo, r.nuevo);
  end loop;
end $$;

-- ---------- 6) pendientes por renglon sin signo ----------
do $$
declare d text; n int;
  v1 text := 'sum(oi.cantidad - oi.recibido) pendiente';
  v2 text := 'sum(oi.cantidad - coalesce(oi.recibido,0))';
begin
  d := pg_get_functiondef('"GP2".oc_bundle()'::regprocedure);
  n := (length(d) - length(replace(d, v1, ''))) / length(v1);
  if n <> 1 then raise exception 'oc_bundle: se esperaba 1 y hay %', n; end if;
  execute replace(d, v1, 'sum(greatest(oi.cantidad - oi.recibido, 0)) pendiente');

  select pg_get_functiondef(p.oid) into d from pg_proc p
   where p.pronamespace = '"GP2"'::regnamespace and p.proname = 'tablet_bundle';
  n := (length(d) - length(replace(d, v2, ''))) / length(v2);
  if n < 1 then raise exception 'tablet_bundle: no encontre el pendiente'; end if;
  execute replace(d, v2, 'sum(greatest(oi.cantidad - coalesce(oi.recibido,0), 0))');
end $$;

-- ---------- 7) datos: OC N° 2 con lo que entro de verdad ----------
-- PC4  (renglon 159): recepcion 17102, movimiento 85614 = 2.806 (remito 2.800)
-- PEP9 (renglon 160): recepcion 17103, movimiento 85616 = 1.342 (remito 1.300, OC decia 1.250)
update "GP2".orden_compra_item i set recibido = m.cantidad
  from "GP2".movimiento m
 where (i.id, m.id) in ((159, 85614), (160, 85616));
insert into "GP2".oc_item_recepcion(oc_item_id, movimiento_id, cantidad)
select v.item, v.mov, m.cantidad
  from (values (159::bigint, 85614::bigint), (160, 85616)) v(item, mov)
  join "GP2".movimiento m on m.id = v.mov
 where not exists (select 1 from "GP2".oc_item_recepcion x where x.movimiento_id = v.mov);
