-- =====================================================================
-- TABLAS del schema GP2 (DDL reconstruido de pg_catalog: columnas, identity, defaults, constraints) — export automatico 2026-08-31 desde Supabase (hrxfctzncixxqmpfhskv)
-- Respaldo/referencia. La fuente de verdad es la base; regenerar al cambiar el schema.
-- =====================================================================

-- ---------- _bak_inventario_maximo_20260830 ----------
create table "GP2"._bak_inventario_maximo_20260830 (
  id bigint,
  componente_id bigint,
  ubicacion_id bigint,
  cantidad numeric,
  maximo numeric,
  maximo_origen text,
  bak_en timestamp with time zone
);

-- ---------- _bak_maxcomp_transitos ----------
create table "GP2"._bak_maxcomp_transitos (
  max_comp_id bigint
);

-- ---------- _bak_ruta_paso_transitos ----------
create table "GP2"._bak_ruta_paso_transitos (
  id bigint,
  comp_entrada_id bigint,
  comp_salida_id bigint
);

-- ---------- agente_propuestas ----------
create table "GP2".agente_propuestas (
  codigo text not null,
  agente text not null default 'gp2-diario'::text,
  titulo text not null,
  detalle text,
  impacto text,
  esfuerzo text,
  ubicacion text,
  estado text not null default 'pendiente'::text,
  rama text,
  creado_en timestamp with time zone not null default now(),
  actualizado_en timestamp with time zone,
  constraint agente_propuestas_pkey PRIMARY KEY (codigo),
  constraint agente_propuestas_codigo_check CHECK ((codigo ~ '^[0-9]{4}$'::text)),
  constraint agente_propuestas_estado_check CHECK ((estado = ANY (ARRAY['pendiente'::text, 'lista'::text, 'hecha'::text, 'descartada'::text])))
);

-- ---------- articulo ----------
create table "GP2".articulo (
  id bigint generated by default as identity not null,
  codigo text not null,
  familia text,
  componente_caja_id bigint,
  articulos_por_caja integer,
  estadistica_madre_uni_mes numeric,
  -- true = ya no se fabrica (ej. 119 y 809: ahora se importan — ver sufijo E en CONOCIMIENTO). Sin fila activa en Est Madre no generan consumo; el flag es para que las pantallas los distingan.
  discontinuado boolean not null default false,
  constraint articulo_pkey PRIMARY KEY (id)
);

-- ---------- articulo_componente ----------
create table "GP2".articulo_componente (
  id bigint generated by default as identity not null,
  articulo_id bigint,
  componente_id bigint,
  cantidad numeric,
  constraint articulo_componente_pkey PRIMARY KEY (id),
  constraint articulo_componente_articulo_id_fkey FOREIGN KEY (articulo_id) REFERENCES "GP2".articulo(id),
  constraint articulo_componente_componente_id_fkey FOREIGN KEY (componente_id) REFERENCES "GP2".componente(id)
);

-- ---------- carton_categoria ----------
create table "GP2".carton_categoria (
  nombre text not null,
  formato text not null,
  mezcla_libre boolean not null default false,
  constraint carton_categoria_pkey PRIMARY KEY (nombre),
  constraint carton_categoria_formato_fkey FOREIGN KEY (formato) REFERENCES "GP2".carton_formato(nombre)
);

-- ---------- carton_formato ----------
create table "GP2".carton_formato (
  nombre text not null,
  pliegos_multiplo integer not null,
  codigo_multiplo integer not null,
  min_codigo_x_multiplo integer not null,
  nota text,
  constraint carton_formato_pkey PRIMARY KEY (nombre)
);
