-- =====================================================================
-- TABLAS del schema GP2 (DDL reconstruido de pg_catalog: columnas, identity, defaults, constraints) — export automatico 2026-08-29 desde Supabase (hrxfctzncixxqmpfhskv)
-- Respaldo/referencia. La fuente de verdad es la base; regenerar al cambiar el schema.
-- =====================================================================

-- ---------- _bak_maxcomp_transitos ----------
create table "GP2"._bak_maxcomp_transitos (
  max_comp_id bigint
);

-- ---------- _bak_ruta_paso_transitos ----------
create table "GP2"._bak_ruta_paso_transitos (
  id bigint,
  comp_entrada_id bigint,
  comp_salida_id bigint
);

-- ---------- articulo ----------
create table "GP2".articulo (
  id bigint generated by default as identity not null,
  codigo text not null,
  familia text,
  componente_caja_id bigint,
  articulos_por_caja integer,
  estadistica_madre_uni_mes numeric,
  constraint articulo_pkey PRIMARY KEY (id)
);

-- ---------- articulo_componente ----------
create table "GP2".articulo_componente (
  id bigint generated by default as identity not null,
  articulo_id bigint,
  componente_id bigint,
  cantidad numeric,
  constraint articulo_componente_pkey PRIMARY KEY (id),
  constraint articulo_componente_articulo_id_fkey FOREIGN KEY (articulo_id) REFERENCES "GP2".articulo(id),
  constraint articulo_componente_componente_id_fkey FOREIGN KEY (componente_id) REFERENCES "GP2".componente(id)
);

-- ---------- carton_categoria ----------
create table "GP2".carton_categoria (
  nombre text not null,
  formato text not null,
  mezcla_libre boolean not null default false,
  constraint carton_categoria_pkey PRIMARY KEY (nombre),
  constraint carton_categoria_formato_fkey FOREIGN KEY (formato) REFERENCES "GP2".carton_formato(nombre)
);

-- ---------- carton_formato ----------
create table "GP2".carton_formato (
  nombre text not null,
  pliegos_multiplo integer not null,
  codigo_multiplo integer not null,
  min_codigo_x_multiplo integer not null,
  nota text,
  constraint carton_formato_pkey PRIMARY KEY (nombre)
);

-- ---------- componente ----------
create table "GP2".componente (
  id bigint generated by default as identity not null,
  codigo text,
  descripcion text,
  sector_id bigint,
  unidad_medida text,
  kg_x_uni numeric,
  uni_x_cajon numeric,
  proveedor text,
  carton_formato text,
  carton_categoria text,
  constraint componente_pkey PRIMARY KEY (id),
  constraint componente_carton_categoria_fkey FOREIGN KEY (carton_categoria) REFERENCES "GP2".carton_categoria(nombre),
  constraint componente_carton_formato_fkey FOREIGN KEY (carton_formato) REFERENCES "GP2".carton_formato(nombre),
  constraint componente_sector_id_fkey FOREIGN KEY (sector_id) REFERENCES "GP2".sector(id)
);

-- ---------- componente_bom ----------
create table "GP2".componente_bom (
  id bigint generated by default as identity not null,
  componente_padre_id bigint,
  componente_hijo_id bigint,
  cantidad numeric,
  constraint componente_bom_pkey PRIMARY KEY (id),
  constraint componente_bom_componente_hijo_id_fkey FOREIGN KEY (componente_hijo_id) REFERENCES "GP2".componente(id),
  constraint componente_bom_componente_padre_id_fkey FOREIGN KEY (componente_padre_id) REFERENCES "GP2".componente(id)
);

-- ---------- contraparte_alias ----------
create table "GP2".contraparte_alias (
  alias text not null,
  tipo text not null,
  ref_id bigint,
  constraint contraparte_alias_pkey PRIMARY KEY (alias),
  constraint contraparte_alias_tipo_check CHECK ((tipo = ANY (ARRAY['tallerista'::text, 'proveedor_at'::text, 'proveedor_servicio'::text, 'interno'::text])))
);

-- ---------- devolucion_tallerista ----------
create table "GP2".devolucion_tallerista (
  id bigint generated always as identity not null,
  movimiento_id bigint not null,
  tallerista_id bigint not null,
  destino text not null,
  motivo text,
  creado_en timestamp with time zone not null default now(),
  constraint devolucion_tallerista_pkey PRIMARY KEY (id),
  constraint devolucion_tallerista_movimiento_id_fkey FOREIGN KEY (movimiento_id) REFERENCES "GP2".movimiento(id) ON DELETE CASCADE,
  constraint devolucion_tallerista_tallerista_id_fkey FOREIGN KEY (tallerista_id) REFERENCES "GP2".tallerista(id),
  constraint devolucion_tallerista_destino_check CHECK ((destino = ANY (ARRAY['sector'::text, 'analizar'::text])))
);

-- ---------- empleado ----------
create table "GP2".empleado (
  id bigint generated always as identity not null,
  legajo text not null,
  nombre text not null,
  activo boolean not null default true,
  tipo text,
  hora_entrada time without time zone,
  constraint empleado_legajo_key UNIQUE (legajo),
  constraint empleado_pkey PRIMARY KEY (id)
);

-- ---------- est_madre ----------
create table "GP2".est_madre (
  cod text not null,
  proy_cajas_mes numeric,
  uxb integer,
  proy_uni_mes numeric,
  actualizado timestamp with time zone,
  copiado_en timestamp with time zone not null default now(),
  constraint proyeccion_venta_pkey PRIMARY KEY (cod)
);

-- ---------- familia ----------
create table "GP2".familia (
  id bigint generated by default as identity not null,
  nombre text not null,
  constraint familia_pkey PRIMARY KEY (id)
);

-- ---------- fleje_detalle ----------
create table "GP2".fleje_detalle (
  componente_id bigint not null,
  n_fleje text,
  medida_mm text,
  proveedor text,
  cons_mensual numeric,
  kg_x_cajon numeric,
  cod_isis text,
  actualizado_en timestamp with time zone default now(),
  kg_x_uni numeric,
  kg_uni_desp numeric,
  descripcion_parte text,
  constraint fleje_detalle_pkey PRIMARY KEY (componente_id),
  constraint fleje_detalle_componente_id_fkey FOREIGN KEY (componente_id) REFERENCES "GP2".componente(id) ON DELETE CASCADE
);

-- ---------- inventario ----------
create table "GP2".inventario (
  id bigint not null default nextval('"GP2".inventario_id_seq'::regclass),
  componente_id bigint,
  ubicacion_id bigint,
  cantidad numeric default 0,
  minimo numeric default 0,
  actualizado_en timestamp with time zone,
  maximo numeric,
  maximo_origen text,
  constraint inventario_pkey PRIMARY KEY (id),
  constraint inventario_componente_id_fkey FOREIGN KEY (componente_id) REFERENCES "GP2".componente(id),
  constraint inventario_ubicacion_id_fkey FOREIGN KEY (ubicacion_id) REFERENCES "GP2".ubicacion(id)
);

-- ---------- matriz ----------
create table "GP2".matriz (
  id bigint generated by default as identity not null,
  n_matriz text not null,
  descripcion text,
  tipo text,
  partes_por_kilo_de_fleje numeric,
  primera_del_fleje text,
  tiempo_historico numeric,
  uni_x_golpe numeric,
  constraint matriz_pkey PRIMARY KEY (id)
);

-- ---------- movimiento ----------
create table "GP2".movimiento (
  id bigint not null default nextval('"GP2".movimiento_id_seq'::regclass),
  fecha timestamp with time zone,
  tipo_mov text,
  comp_id bigint,
  ubic_origen_id bigint,
  ubic_destino_id bigint,
  cantidad numeric,
  comp_transformado_id bigint,
  cantidad_transformada numeric,
  unidad_origen text,
  unidad_destino text,
  _delta_orig numeric,
  _delta_dest numeric,
  cajones numeric,
  faltante boolean not null default false,
  constraint movimiento_pkey PRIMARY KEY (id),
  constraint movimiento_comp_id_fkey FOREIGN KEY (comp_id) REFERENCES "GP2".componente(id),
  constraint movimiento_comp_transformado_id_fkey FOREIGN KEY (comp_transformado_id) REFERENCES "GP2".componente(id),
  constraint movimiento_ubic_destino_id_fkey FOREIGN KEY (ubic_destino_id) REFERENCES "GP2".ubicacion(id),
  constraint movimiento_ubic_origen_id_fkey FOREIGN KEY (ubic_origen_id) REFERENCES "GP2".ubicacion(id)
);

-- ---------- orden_compra ----------
create table "GP2".orden_compra (
  id bigint generated by default as identity not null,
  numero integer not null,
  proveedor text,
  rubro text,
  estado text not null default 'borrador'::text,
  nota text,
  creado_en timestamp with time zone not null default now(),
  creado_por text,
  constraint orden_compra_pkey PRIMARY KEY (id),
  constraint orden_compra_estado_check CHECK ((estado = ANY (ARRAY['borrador'::text, 'enviada'::text, 'recibida'::text, 'anulada'::text])))
);

-- ---------- orden_compra_item ----------
create table "GP2".orden_compra_item (
  id bigint generated by default as identity not null,
  oc_id bigint not null,
  componente_id bigint not null,
  cantidad numeric not null,
  unidad text not null default 'uni'::text,
  recibido numeric not null default 0,
  constraint orden_compra_item_pkey PRIMARY KEY (id),
  constraint orden_compra_item_componente_id_fkey FOREIGN KEY (componente_id) REFERENCES "GP2".componente(id),
  constraint orden_compra_item_oc_id_fkey FOREIGN KEY (oc_id) REFERENCES "GP2".orden_compra(id) ON DELETE CASCADE,
  constraint orden_compra_item_cantidad_check CHECK ((cantidad > (0)::numeric))
);

-- ---------- parametro ----------
create table "GP2".parametro (
  clave text not null,
  valor numeric not null,
  descripcion text,
  constraint parametro_pkey PRIMARY KEY (clave)
);

-- ---------- pedido ----------
create table "GP2".pedido (
  id bigint not null default nextval('"GP2".pedido_id_seq'::regclass),
  articulo_id bigint,
  unidades integer,
  estado text default 'pendiente'::text,
  fecha_pedido date,
  fecha_entrega date,
  nota text,
  constraint pedido_pkey PRIMARY KEY (id),
  constraint pedido_articulo_id_fkey FOREIGN KEY (articulo_id) REFERENCES "GP2".articulo(id)
);

-- ---------- precio_proveedor ----------
create table "GP2".precio_proveedor (
  id bigint generated by default as identity not null,
  rubro text,
  cod_prov text,
  producto text not null,
  precio numeric,
  moneda text,
  fecha_lista date,
  componente_id bigint,
  copiado_en timestamp with time zone default now(),
  constraint precio_proveedor_pkey PRIMARY KEY (id),
  constraint precio_proveedor_componente_id_fkey FOREIGN KEY (componente_id) REFERENCES "GP2".componente(id)
);

-- ---------- produccion ----------
create table "GP2".produccion (
  id bigint not null default nextval('"GP2".produccion_id_seq'::regclass),
  espejo_id bigint,
  fecha timestamp with time zone,
  legajo text,
  nombre_empleado text,
  matriz_raw text,
  nombre_matriz text,
  matriz_id bigint,
  uni real,
  premio double precision,
  tiempo_toma real,
  tiempo_historico real,
  hora_inicio time without time zone,
  hora_fin time without time zone,
  anular_tiempo boolean,
  segundos_historico numeric,
  segundos_trabajados numeric,
  segundos_tiempo_muerto numeric,
  dia integer,
  mes integer,
  quincena integer,
  id_ejecucion text,
  eliminar text,
  revisado boolean,
  fecha_inicio timestamp with time zone,
  fecha_fin timestamp with time zone,
  origen_created_at timestamp with time zone,
  espejado_en timestamp with time zone default now(),
  constraint produccion_espejo_id_key UNIQUE (espejo_id),
  constraint produccion_pkey PRIMARY KEY (id),
  constraint produccion_matriz_id_fkey FOREIGN KEY (matriz_id) REFERENCES "GP2".matriz(id)
);

-- ---------- proveedor_at ----------
create table "GP2".proveedor_at (
  id bigint generated always as identity not null,
  cod_prov text,
  nombre text not null,
  activo boolean not null default true,
  notas text,
  constraint proveedor_at_nombre_key UNIQUE (nombre),
  constraint proveedor_at_pkey PRIMARY KEY (id)
);

-- ---------- proveedor_insumo ----------
create table "GP2".proveedor_insumo (
  nombre text not null,
  informa_rollos boolean not null default false,
  activo boolean not null default true,
  factura_uni boolean not null default false,
  modo_control text not null default 'ninguno'::text,
  constraint proveedor_insumo_pkey PRIMARY KEY (nombre),
  constraint proveedor_insumo_modo_control_chk CHECK ((modo_control = ANY (ARRAY['ninguno'::text, 'rollos_remito'::text, 'pesaje'::text, 'peso_total'::text, 'pendiente'::text])))
);

-- ---------- proveedor_servicio ----------
create table "GP2".proveedor_servicio (
  id bigint generated by default as identity not null,
  cod_prov text,
  nombre text,
  proceso text,
  constraint proveedor_servicio_pkey PRIMARY KEY (id)
);

-- ---------- proveedor_servicio_alias ----------
create table "GP2".proveedor_servicio_alias (
  id bigint generated always as identity not null,
  nombre_viejo text not null,
  ps_id bigint,
  ps_nombre text not null,
  confianza text not null default 'confirmado'::text,
  nota text,
  constraint proveedor_servicio_alias_nombre_viejo_key UNIQUE (nombre_viejo),
  constraint proveedor_servicio_alias_pkey PRIMARY KEY (id),
  constraint proveedor_servicio_alias_ps_id_fkey FOREIGN KEY (ps_id) REFERENCES "GP2".proveedor_servicio(id)
);

-- ---------- recepcion_control ----------
create table "GP2".recepcion_control (
  id bigint generated always as identity not null,
  recepcion_id bigint not null,
  peso_balanza numeric not null,
  controlado_por text,
  controlado_en timestamp with time zone not null default now(),
  nota text,
  nro_pallet integer not null default 1,
  constraint recepcion_control_pallet_uk UNIQUE (recepcion_id, nro_pallet),
  constraint recepcion_control_pkey PRIMARY KEY (id),
  constraint recepcion_control_recepcion_id_fkey FOREIGN KEY (recepcion_id) REFERENCES "GP2".recepcion_insumo(id) ON DELETE CASCADE,
  constraint recepcion_control_peso_balanza_check CHECK ((peso_balanza > (0)::numeric))
);

-- ---------- recepcion_control_rollo ----------
create table "GP2".recepcion_control_rollo (
  id bigint generated always as identity not null,
  control_id bigint not null,
  cantidad integer not null,
  kg_por_rollo numeric not null,
  constraint recepcion_control_rollo_pkey PRIMARY KEY (id),
  constraint recepcion_control_rollo_control_id_fkey FOREIGN KEY (control_id) REFERENCES "GP2".recepcion_control(id) ON DELETE CASCADE,
  constraint recepcion_control_rollo_cantidad_check CHECK ((cantidad > 0)),
  constraint recepcion_control_rollo_kg_por_rollo_check CHECK ((kg_por_rollo > (0)::numeric))
);

-- ---------- recepcion_insumo ----------
create table "GP2".recepcion_insumo (
  id bigint not null default nextval('"GP2".recepcion_insumo_id_seq'::regclass),
  fecha timestamp with time zone not null default now(),
  componente_id bigint not null,
  proveedor text,
  remito text,
  cantidad numeric not null,
  unidad text not null default 'uni'::text,
  movimiento_id bigint,
  created_at timestamp with time zone default now(),
  rollos integer,
  pallets integer,
  constraint recepcion_insumo_pkey PRIMARY KEY (id),
  constraint recepcion_insumo_componente_id_fkey FOREIGN KEY (componente_id) REFERENCES "GP2".componente(id),
  constraint recepcion_insumo_pallets_check CHECK (((pallets IS NULL) OR (pallets > 0)))
);

-- ---------- rollo_evento ----------
create table "GP2".rollo_evento (
  id bigint generated always as identity not null,
  fecha timestamp with time zone not null default now(),
  componente_id bigint not null,
  kg_por_rollo numeric not null,
  delta integer not null,
  motivo text not null,
  legajo text,
  control_rollo_id bigint,
  nota text,
  constraint rollo_evento_pkey PRIMARY KEY (id),
  constraint rollo_evento_componente_id_fkey FOREIGN KEY (componente_id) REFERENCES "GP2".componente(id),
  constraint rollo_evento_control_rollo_id_fkey FOREIGN KEY (control_rollo_id) REFERENCES "GP2".recepcion_control_rollo(id) ON DELETE SET NULL,
  constraint rollo_evento_delta_check CHECK ((delta <> 0)),
  constraint rollo_evento_kg_por_rollo_check CHECK ((kg_por_rollo > (0)::numeric)),
  constraint rollo_evento_motivo_check CHECK ((motivo = ANY (ARRAY['inicial'::text, 'recepcion'::text, 'toma_operario'::text, 'ajuste'::text, 'devolucion'::text])))
);

-- ---------- rollo_uso ----------
create table "GP2".rollo_uso (
  id bigint generated always as identity not null,
  legajo text not null,
  componente_id bigint not null,
  kg_por_rollo numeric not null,
  matriz_raw text,
  ts_inicio timestamp with time zone not null default now(),
  ts_fin timestamp with time zone,
  quedo_resto boolean,
  uni_producidas numeric,
  uni_esperadas numeric,
  rollo_evento_id bigint,
  constraint rollo_uso_pkey PRIMARY KEY (id),
  constraint rollo_uso_componente_id_fkey FOREIGN KEY (componente_id) REFERENCES "GP2".componente(id),
  constraint rollo_uso_rollo_evento_id_fkey FOREIGN KEY (rollo_evento_id) REFERENCES "GP2".rollo_evento(id)
);

-- ---------- ruta ----------
create table "GP2".ruta (
  id bigint generated by default as identity not null,
  nombre text,
  articulo_id bigint,
  constraint ruta_pkey PRIMARY KEY (id),
  constraint ruta_articulo_id_fkey FOREIGN KEY (articulo_id) REFERENCES "GP2".articulo(id)
);

-- ---------- ruta_confirmada ----------
create table "GP2".ruta_confirmada (
  id bigint generated always as identity not null,
  firma text not null,
  articulo text not null default ''::text,
  fleje text not null default ''::text,
  confirmado_por text not null,
  confirmado_en timestamp with time zone not null default now(),
  constraint ruta_confirmada_firma_key UNIQUE (firma),
  constraint ruta_confirmada_pkey PRIMARY KEY (id)
);

-- ---------- ruta_paso ----------
create table "GP2".ruta_paso (
  id bigint generated by default as identity not null,
  ruta_id bigint,
  orden integer,
  tipo_paso text,
  componente_fleje_id bigint,
  matriz_id bigint,
  proveedor_id bigint,
  tallerista_id bigint,
  comp_entrada_id bigint,
  comp_salida_id bigint,
  articulo_id bigint,
  constraint ruta_paso_pkey PRIMARY KEY (id),
  constraint ruta_paso_articulo_id_fkey FOREIGN KEY (articulo_id) REFERENCES "GP2".articulo(id),
  constraint ruta_paso_comp_entrada_id_fkey FOREIGN KEY (comp_entrada_id) REFERENCES "GP2".componente(id),
  constraint ruta_paso_comp_salida_id_fkey FOREIGN KEY (comp_salida_id) REFERENCES "GP2".componente(id),
  constraint ruta_paso_componente_fleje_id_fkey FOREIGN KEY (componente_fleje_id) REFERENCES "GP2".componente(id),
  constraint ruta_paso_matriz_id_fkey FOREIGN KEY (matriz_id) REFERENCES "GP2".matriz(id),
  constraint ruta_paso_proveedor_id_fkey FOREIGN KEY (proveedor_id) REFERENCES "GP2".proveedor_servicio(id),
  constraint ruta_paso_ruta_id_fkey FOREIGN KEY (ruta_id) REFERENCES "GP2".ruta(id),
  constraint ruta_paso_tallerista_id_fkey FOREIGN KEY (tallerista_id) REFERENCES "GP2".tallerista(id)
);

-- ---------- ruta_problema ----------
create table "GP2".ruta_problema (
  id bigint generated always as identity not null,
  firma text not null,
  articulo text default ''::text,
  fleje text default ''::text,
  problema text not null default '(pendiente de revisar)'::text,
  estado text not null default 'pendiente'::text,
  reportado_por text not null,
  reportado_en timestamp with time zone not null default now(),
  resuelto_en timestamp with time zone,
  constraint ruta_problema_pkey PRIMARY KEY (id),
  constraint ruta_problema_estado_check CHECK ((estado = ANY (ARRAY['pendiente'::text, 'resuelto'::text])))
);

-- ---------- sector ----------
create table "GP2".sector (
  id bigint generated by default as identity not null,
  tipo text not null,
  nombre text not null,
  constraint sector_pkey PRIMARY KEY (id)
);

-- ---------- tallerista ----------
create table "GP2".tallerista (
  id bigint generated by default as identity not null,
  cod_prov text,
  nombre text not null,
  clase text not null default 'tallerista'::text,
  constraint tallerista_pkey PRIMARY KEY (id)
);

-- ---------- tallerista_alias ----------
create table "GP2".tallerista_alias (
  alias text not null,
  tallerista_id bigint,
  constraint tallerista_alias_pkey PRIMARY KEY (alias),
  constraint tallerista_alias_tallerista_id_fkey FOREIGN KEY (tallerista_id) REFERENCES "GP2".tallerista(id)
);

-- ---------- ubicacion ----------
create table "GP2".ubicacion (
  id bigint generated by default as identity not null,
  tipo text,
  ref_id bigint,
  nombre text,
  meses_minimo numeric,
  meses_stock numeric,
  constraint ubicacion_pkey PRIMARY KEY (id)
);

-- ---------- virgilio_espejo_pend ----------
create table "GP2".virgilio_espejo_pend (
  id bigint generated always as identity not null,
  entrega_id bigint,
  fecha text,
  nombre_tall text,
  cod text,
  cajas numeric,
  motivo text,
  creado_en timestamp with time zone not null default now(),
  constraint virgilio_espejo_pend_pkey PRIMARY KEY (id)
);


-- ============ INDICES (no asociados a constraints) ============

CREATE INDEX idx_articulo_componente_articulo_id ON "GP2".articulo_componente USING btree (articulo_id);
CREATE INDEX idx_articulo_componente_componente_id ON "GP2".articulo_componente USING btree (componente_id);
CREATE INDEX idx_carton_categoria_formato ON "GP2".carton_categoria USING btree (formato);
CREATE INDEX idx_componente_bom_componente_hijo_id ON "GP2".componente_bom USING btree (componente_hijo_id);
CREATE INDEX idx_componente_bom_componente_padre_id ON "GP2".componente_bom USING btree (componente_padre_id);
CREATE INDEX idx_componente_carton_categoria ON "GP2".componente USING btree (carton_categoria);
CREATE INDEX idx_componente_carton_formato ON "GP2".componente USING btree (carton_formato);
CREATE INDEX idx_componente_sector_id ON "GP2".componente USING btree (sector_id);
CREATE INDEX idx_devolucion_tallerista_movimiento_id ON "GP2".devolucion_tallerista USING btree (movimiento_id);
CREATE INDEX idx_devolucion_tallerista_tallerista_id ON "GP2".devolucion_tallerista USING btree (tallerista_id);
CREATE INDEX idx_inventario_ubicacion_id ON "GP2".inventario USING btree (ubicacion_id);
CREATE INDEX idx_movimiento_comp_id ON "GP2".movimiento USING btree (comp_id);
CREATE INDEX idx_movimiento_comp_transformado_id ON "GP2".movimiento USING btree (comp_transformado_id);
CREATE INDEX idx_movimiento_ubic_destino_id ON "GP2".movimiento USING btree (ubic_destino_id);
CREATE INDEX idx_movimiento_ubic_origen_id ON "GP2".movimiento USING btree (ubic_origen_id);
CREATE INDEX idx_orden_compra_item_componente_id ON "GP2".orden_compra_item USING btree (componente_id);
CREATE INDEX idx_orden_compra_item_oc_id ON "GP2".orden_compra_item USING btree (oc_id);
CREATE INDEX idx_pedido_articulo_id ON "GP2".pedido USING btree (articulo_id);
CREATE INDEX idx_precio_proveedor_componente_id ON "GP2".precio_proveedor USING btree (componente_id);
CREATE INDEX idx_produccion_matriz_id ON "GP2".produccion USING btree (matriz_id);
CREATE UNIQUE INDEX uq_produccion_id_ejecucion ON "GP2".produccion USING btree (id_ejecucion) WHERE (id_ejecucion IS NOT NULL);
CREATE INDEX idx_proveedor_servicio_alias_ps_id ON "GP2".proveedor_servicio_alias USING btree (ps_id);
CREATE INDEX idx_recepcion_insumo_componente_id ON "GP2".recepcion_insumo USING btree (componente_id);
CREATE INDEX idx_rollo_evento_control_rollo_id ON "GP2".rollo_evento USING btree (control_rollo_id);
CREATE INDEX idx_rollo_uso_componente_id ON "GP2".rollo_uso USING btree (componente_id);
CREATE INDEX idx_rollo_uso_rollo_evento_id ON "GP2".rollo_uso USING btree (rollo_evento_id);
CREATE INDEX idx_ruta_articulo_id ON "GP2".ruta USING btree (articulo_id);
CREATE INDEX idx_ruta_paso_articulo_id ON "GP2".ruta_paso USING btree (articulo_id);
CREATE INDEX idx_ruta_paso_comp_entrada_id ON "GP2".ruta_paso USING btree (comp_entrada_id);
CREATE INDEX idx_ruta_paso_comp_salida_id ON "GP2".ruta_paso USING btree (comp_salida_id);
CREATE INDEX idx_ruta_paso_componente_fleje_id ON "GP2".ruta_paso USING btree (componente_fleje_id);
CREATE INDEX idx_ruta_paso_matriz_id ON "GP2".ruta_paso USING btree (matriz_id);
CREATE INDEX idx_ruta_paso_proveedor_id ON "GP2".ruta_paso USING btree (proveedor_id);
CREATE INDEX idx_ruta_paso_ruta_id ON "GP2".ruta_paso USING btree (ruta_id);
CREATE INDEX idx_ruta_paso_tallerista_id ON "GP2".ruta_paso USING btree (tallerista_id);
CREATE INDEX idx_tallerista_alias_tallerista_id ON "GP2".tallerista_alias USING btree (tallerista_id);
CREATE UNIQUE INDEX inventario_comp_ubic_uk ON "GP2".inventario USING btree (componente_id, ubicacion_id);
CREATE INDEX recepcion_control_rollo_control_idx ON "GP2".recepcion_control_rollo USING btree (control_id);
CREATE INDEX rollo_evento_comp_idx ON "GP2".rollo_evento USING btree (componente_id, kg_por_rollo, fecha);
CREATE INDEX rollo_uso_abierto_idx ON "GP2".rollo_uso USING btree (legajo) WHERE (ts_fin IS NULL);
CREATE INDEX ruta_problema_estado_idx ON "GP2".ruta_problema USING btree (estado);
CREATE INDEX ruta_problema_firma_idx ON "GP2".ruta_problema USING btree (firma);

-- ============ TRIGGERS ============

CREATE TRIGGER trg_maximos_est_madre AFTER INSERT OR DELETE OR UPDATE ON "GP2".est_madre FOR EACH STATEMENT EXECUTE FUNCTION "GP2".fn_recalc_maximos_insumos();

CREATE TRIGGER trg_maximos_receta AFTER INSERT OR DELETE OR UPDATE ON "GP2".articulo_componente FOR EACH STATEMENT EXECUTE FUNCTION "GP2".fn_recalc_maximos_insumos();

CREATE TRIGGER trg_maximos_rutas AFTER INSERT OR DELETE OR UPDATE ON "GP2".ruta_paso FOR EACH STATEMENT EXECUTE FUNCTION "GP2".fn_recalc_maximos_insumos();

CREATE TRIGGER trg_movimiento_aplicar AFTER INSERT OR DELETE OR UPDATE ON "GP2".movimiento FOR EACH ROW EXECUTE FUNCTION "GP2".fn_movimiento_aplicar();

CREATE TRIGGER trg_movimiento_calc BEFORE INSERT OR UPDATE ON "GP2".movimiento FOR EACH ROW EXECUTE FUNCTION "GP2".fn_movimiento_calc();

CREATE TRIGGER trg_rollo_desde_control AFTER INSERT OR DELETE OR UPDATE ON "GP2".recepcion_control_rollo FOR EACH ROW EXECUTE FUNCTION "GP2".fn_rollo_desde_control();


-- ============ ROW LEVEL SECURITY ============

alter table "GP2"._bak_maxcomp_transitos enable row level security;
alter table "GP2"._bak_ruta_paso_transitos enable row level security;
alter table "GP2".articulo enable row level security;
alter table "GP2".articulo_componente enable row level security;
alter table "GP2".carton_categoria enable row level security;
alter table "GP2".carton_formato enable row level security;
alter table "GP2".componente enable row level security;
alter table "GP2".componente_bom enable row level security;
alter table "GP2".contraparte_alias enable row level security;
alter table "GP2".devolucion_tallerista enable row level security;
alter table "GP2".empleado enable row level security;
alter table "GP2".est_madre enable row level security;
alter table "GP2".familia enable row level security;
alter table "GP2".fleje_detalle enable row level security;
alter table "GP2".inventario enable row level security;
alter table "GP2".matriz enable row level security;
alter table "GP2".movimiento enable row level security;
alter table "GP2".orden_compra enable row level security;
alter table "GP2".orden_compra_item enable row level security;
alter table "GP2".parametro enable row level security;
alter table "GP2".pedido enable row level security;
alter table "GP2".precio_proveedor enable row level security;
alter table "GP2".produccion enable row level security;
alter table "GP2".proveedor_at enable row level security;
alter table "GP2".proveedor_insumo enable row level security;
alter table "GP2".proveedor_servicio enable row level security;
alter table "GP2".proveedor_servicio_alias enable row level security;
alter table "GP2".recepcion_control enable row level security;
alter table "GP2".recepcion_control_rollo enable row level security;
alter table "GP2".recepcion_insumo enable row level security;
alter table "GP2".rollo_evento enable row level security;
alter table "GP2".rollo_uso enable row level security;
alter table "GP2".ruta enable row level security;
alter table "GP2".ruta_confirmada enable row level security;
alter table "GP2".ruta_paso enable row level security;
alter table "GP2".ruta_problema enable row level security;
alter table "GP2".sector enable row level security;
alter table "GP2".tallerista enable row level security;
alter table "GP2".tallerista_alias enable row level security;
alter table "GP2".ubicacion enable row level security;
alter table "GP2".virgilio_espejo_pend enable row level security;

-- ============ POLICIES ============

create policy p_empleado_insert on "GP2".empleado for insert to anon, authenticated with check (true);
create policy p_empleado_update on "GP2".empleado for update to anon, authenticated using (true) with check (true);
create policy p_gp2_select on "GP2".ruta_problema for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".proveedor_at for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".contraparte_alias for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".orden_compra for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".orden_compra_item for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".carton_categoria for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".precio_proveedor for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".movimiento for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".tallerista for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".tallerista_alias for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".devolucion_tallerista for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".recepcion_control_rollo for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".parametro for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".empleado for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".proveedor_servicio for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".inventario for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".rollo_evento for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".recepcion_control for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".ruta for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".recepcion_insumo for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".pedido for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".fleje_detalle for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".est_madre for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".virgilio_espejo_pend for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".carton_formato for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".sector for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".articulo for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".articulo_componente for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".ruta_paso for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".componente for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".proveedor_insumo for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".produccion for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".proveedor_servicio_alias for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2"._bak_ruta_paso_transitos for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2"._bak_maxcomp_transitos for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".familia for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".matriz for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".componente_bom for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".ubicacion for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".rollo_uso for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".ruta_confirmada for select to anon, authenticated using (true);